Thoughts on composition
input-output-hk/cardano-ledger-byron pull request #114
Opened 2018-11-07 17:08 UTC by polinavino

My thoughts on what building a total state transition out of its parts should look like

2018-11-08 09:55 UTC, mdimjasevic commented
@polinavino , I'm trying to understand your proposal. What do you mean when you say _transitions of distinct parts (substates)_? Do you mean `\SubSo` and `\SubSt` are disjoint sets?

2018-11-08 15:20 UTC, polinavino commented
> @polinavino , I'm trying to understand your proposal. What do you mean when you say _transitions of distinct parts (substates)_? Do you mean `\SubSo` and `\SubSt` are disjoint sets?

2018-11-08 15:21 UTC, polinavino commented
Yes! Like the delegation-related part of the ledger state is made up of DState (for individual keys and their delegations) and PState (for stake pools and retiring stake pools).

2018-11-08 16:38 UTC, dnadales commented on specs/semantics/latex/small-step-semantics.tex
> +rule to reflect. In particular, let us consider two substates, $\SubSo$ and
Why is `SubSo` not called `SubS1` and `SubSt` called `SubS1`?

2018-11-08 16:39 UTC, dnadales commented on specs/semantics/latex/small-step-semantics.tex
> +$\SubSt$, with $A, B \in \SubSo$ and $A', B' \in \SubSt$, with all other
Maybe renaming `A` to `A_1` and `A'` to `A_2` make variable types easier to track. Or maybe you could rename `A` to `S_1` and `B` to `S_1'`? Just an idea, feel free to ignore it :D

2018-11-08 16:41 UTC, dnadales commented on specs/semantics/latex/small-step-semantics.tex
> +where $E1 = E1_{s1} \cup E1_{s2}$. These rules can be applied in sequence,
The "where ..." part appears indented in the document.

2018-11-08 16:43 UTC, dnadales commented on specs/semantics/latex/small-step-semantics.tex
> +to give the full $(A,A') \to (B,B')$ transition.
Is having two rules different from having a single rule with the two premises that involve `S1` and `S2`?

2018-11-08 16:45 UTC, dnadales commented on specs/semantics/latex/small-step-semantics.tex
> +to give the full $(A,A') \to (B,B')$ transition.
I think a potential problem I see with this is that you might trigger a lot of `ExampleS1` transitions, and only one `ExampleS2`, then the won't proceed in a lockstep manner (if that's what you intended).

2018-11-08 16:49 UTC, dnadales commented on specs/semantics/latex/small-step-semantics.tex
> +describe the system, anyway).
We might need to make this a bit more precise.

2018-11-08 18:10 UTC, polinavino commented on specs/semantics/latex/small-step-semantics.tex
> +rule to reflect. In particular, let us consider two substates, $\SubSo$ and
I will change this

2018-11-08 18:11 UTC, polinavino commented on specs/semantics/latex/small-step-semantics.tex
> +$\SubSt$, with $A, B \in \SubSo$ and $A', B' \in \SubSt$, with all other
I will rename!

2018-11-08 18:23 UTC, polinavino commented on specs/semantics/latex/small-step-semantics.tex
> +describe the system, anyway).
It is in the new commit (and the one I am about to make which includes your above comments.

2018-11-08 19:16 UTC, polinavino commented on specs/semantics/latex/small-step-semantics.tex
> +to give the full $(A,A') \to (B,B')$ transition.
If there is a single trigger that causes a total $(A,A') \to (B,B')$
transition, that should be explicitly indicated in a separate rule, i think.

2018-11-08 19:29 UTC, dnadales commented
Maybe we should spend half an hour tomorrow to discuss this via video call,
I think it might be easier that way :)

On Thu, Nov 8, 2018, 20:16 polinavino <notifications@github.com wrote:

> *@polinavino* commented on this pull request.
> ------------------------------
>
> In specs/semantics/latex/small-step-semantics.tex
> <https://github.com/input-output-hk/cardano-chain/pull/114#discussion_r232026853>
> :
>
> > +of the form  $(A, A') \to (B, B')$,  we would make two rules:
> +
> +\[
> +  \inference[ExampleS1]
> +    {P(A) & z = f ~ s & \tion[E1_{s1}]{S1}{A}{z}{B}}
> +    {\tion[E1]{S2}{(A,A')}{s}{(B,A')}}
> +\]
> +and
> +\[
> +  \inference[ExampleS2]
> +    {P(A') & z' = f' ~ s' & \tion[E1_{s2}]{S1'}{A'}{z'}{B'}}
> +    {\tion[E1]{S2'}{(A,A')}{s'}{(A,B')}}
> +\]
> +
> +where $E1 = E1_{s1} \cup E1_{s2}$. These rules can be applied in sequence,
> +to give the full $(A,A') \to (B,B')$ transition.
>
> If there is a single trigger that causes a total $(A,A') \to (B,B')$
> transition, that should be explicitly indicated in a separate rule, i
> think.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/input-output-hk/cardano-chain/pull/114#discussion_r232026853>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAKs0_Kye0VlyjxhgTADJUfjPoWApyK_ks5utIMngaJpZM4YS2uL>
> .
>

2018-11-08 19:52 UTC, polinavino commented on specs/semantics/latex/small-step-semantics.tex
> +describe the system, anyway).
Sure! before or after the meeting tomorrow? (I would prefer after)

2018-11-08 20:00 UTC, polinavino commented on specs/semantics/latex/small-step-semantics.tex
> +describe the system, anyway).
Although, the single signal total transition can be done with the two rules too

2018-11-15 16:01 UTC, nc6 requested changes
I would rather not merge this; I think it's not describing the system as described earlier in the paper. It's possible that some of the problems described might persist when re-cast into the existing interpretation framework, but my intuition is that they will all disappear. 

If such problems do persist, then we should at least re-cast this into the same framework as described elsewhere in the paper, or else this is likely to just cause confusion (or maybe this is just me being easily confused!)

2018-11-15 16:01 UTC, nc6 commented on specs/semantics/latex/small-step-semantics.tex
> +by that same signal $c$ (or some related signal $f(c)$).
I don't think this paragraph makes any sense. When we have a transition in the antecedent, we are saying that the existence of such a valid transition is a required condition for the transition in the consequent to be valid. If there are two such transitions, then we have two conditions, but there is no _ordering_ relationship between them. One could impose a _sequencing_ between them (for example, by having the signal for one derived from the RHS of the other), but this is equivalent to writing "let x = 1, y = x" in a mathematical paper; it should not cause us to worry about cases where `x` has been set but `y` has not.

There's also no particular reason why we have to _use_ the results on the RHS of the transitions in the antecedent; I don't think there are any cases where we do it, but it would be fine to for example rely on the transition $A_2 \to B_2$ being valid, but do nothing with the result $B_2$.

In a real implementation, of course, there may be occasion to worry about atomicity, but I think it's not likely to cause problems at this level of granularity (we will presumably commit only at the block level), an is somewhat removed from what we're discussing here.

2018-11-15 16:01 UTC, nc6 commented on specs/semantics/latex/small-step-semantics.tex
> +signal.
This is often the case, but not necessarily. For example, earlier versions of the delegation spec had something like $A \to^{c} B$ and $C \to^{f(B)} D$ in the antecedent.

2018-11-15 16:01 UTC, nc6 commented on specs/semantics/latex/small-step-semantics.tex
> +two antecedent transitions are $c$ and $c'$. The type of the total transition
By `total` you mean the signal in the consequent?

2018-11-15 16:01 UTC, nc6 commented on specs/semantics/latex/small-step-semantics.tex
> +events, such as either by the arrival of
That would violate the condition earlier this paper, which gives each system a particular signal type.

2018-11-15 16:01 UTC, nc6 commented on specs/semantics/latex/small-step-semantics.tex
> +and a $c$-triggered transition in the consequent.
Hmm, I think you perceive the "flow" of reading these rules differently to me (and differently to the 'how to read a rule' section earlier at https://github.com/input-output-hk/cardano-chain/pull/114/files#diff-f592a79369f418b4c5a597a1208271ebR216). I would say that it's the sub-signals (signals for transitions in the antecedent) which are derived from the signal (and other components) on the LHS of the consequent, not the other way around. There is only one 'triggering' signal, that on the consequent. Everything above is then merely a condition on the resulting state (or transition, depending on how you look at it) in the consequent being valid. Thinking about this way, I think, is somewhat simpler and doesn't give any situations such as you describe here.

2018-11-15 16:40 UTC, polinavino commented on specs/semantics/latex/small-step-semantics.tex
> +and a $c$-triggered transition in the consequent.
Yes, sub-signals definitely is the way to describe what the signals in the antecedent should be, I was just thinking that yesterday. Should I take another another crack at writing about this or just leave it?

2018-11-15 18:33 UTC, polinavino commented on specs/semantics/latex/small-step-semantics.tex
> +and a $c$-triggered transition in the consequent.
Like, maybe nail down the definition of sub-signal?

2018-11-22 14:11 UTC, ruhatch commented
@polinavino @nc6 What's the state of this?

2018-11-28 09:09 UTC, nc6 commented
@ruhatch I think I am still failing to understand the core motivation behind this. @polinavino might it be worth having another chat about this?

2018-11-28 13:55 UTC, JaredCorduan commented
We can open this PR up again if/when we get some examples where it is needed. But thanks @polinavino !

2018-11-28 13:55 UTC, closed without merging