Dnadales/cdec 603 heavyweight delegation rules
input-output-hk/cardano-ledger-byron pull request #12
Opened 2018-10-05 11:51 UTC by dnadales

Add rules for heavyweight delegation of block-issuing rights.

2018-10-05 14:04 UTC, nc6 requested changes
I have some questions, a couple of suggestions.

2018-10-05 14:04 UTC, nc6 commented on specs/ledger/latex/simple-ledger-spec.tex
> +    {\ldelegates{\Gamma; c}{\var{vk_s}}{\var{vk_d}}}
Let's have the delegation transition defined somewhere.

2018-10-05 14:04 UTC, nc6 commented on specs/ledger/latex/simple-ledger-spec.tex
> +    & \delegates{c}{vk_s}{vk_d} ~\dot= ~ c = (vk_s, vk_d, \sigma) \wedge \verify{vk_s}{c}{\sigma}
You're using `\dot=` as "is defined to be"?

2018-10-05 14:04 UTC, nc6 commented on specs/ledger/latex/simple-ledger-spec.tex
> +    {\delegates{c}{\var{vk_s}}{\var{vk_d}} \Rightarrow \var{vk} \neq \var{vk_d}
Do we really want an implication here? This is not giving us `delegates c vk_s vk_d`.

2018-10-05 14:04 UTC, nc6 commented on specs/ledger/latex/simple-ledger-spec.tex
> +    {\delegates{c}{\var{vk_s}}{\var{vk_d}} \Rightarrow \var{vk} \neq \var{vk_d}
Also, presumably want `\Rightarrow \var{vk_s} \neq \var{vk_d}`?

2018-10-05 14:11 UTC, nc6 commented
Also, I would suggest we have something like:

- A "delegation-empty" rule which suggests that the empty chain gives `v_k \ldelegates v_k`

This way, the blockchain layer doesn't need to deal with the case of "no delegate"

2018-10-05 14:11 UTC, JaredCorduan commented on specs/ledger/latex/simple-ledger-spec.tex
> +    {\delegates{c}{\var{vk_s}}{\var{vk_d}} \Rightarrow \var{vk} \neq \var{vk_d}
should `vk` be `vk_s`?

2018-10-05 14:15 UTC, JaredCorduan commented on specs/ledger/latex/simple-ledger-spec.tex
> +    & \delegates{c}{vk_s}{vk_d} ~\dot= ~ c = (vk_s, vk_d, \sigma) \wedge \verify{vk_s}{c}{\sigma}
do we use dot-equals elsewhere for denominational equality?  I'm just curious...

2018-10-05 14:15 UTC, dnadales commented on specs/ledger/latex/simple-ledger-spec.tex
> +    {\delegates{c}{\var{vk_s}}{\var{vk_d}} \Rightarrow \var{vk} \neq \var{vk_d}
> Also, presumably want \Rightarrow \var{vk_s} \neq \var{vk_d}?

Why would we need this? (sorry I don't follow :grimacing: )

2018-10-05 14:28 UTC, dnadales commented on specs/ledger/latex/simple-ledger-spec.tex
> +    & \delegates{c}{vk_s}{vk_d} ~\dot= ~ c = (vk_s, vk_d, \sigma) \wedge \verify{vk_s}{c}{\sigma}
Yeah, I just wanted to have a way to distinguish equals by definition from equality between keys. Does that make sense?

2018-10-05 14:29 UTC, dnadales commented on specs/ledger/latex/simple-ledger-spec.tex
> +    {\delegates{c}{\var{vk_s}}{\var{vk_d}} \Rightarrow \var{vk} \neq \var{vk_d}
Actually `vk_d` should be `vk`. See if the changes I pushed make sense now :)

2018-10-05 14:31 UTC, JaredCorduan commented on specs/ledger/latex/simple-ledger-spec.tex
> +    & \delegates{c}{vk_s}{vk_d} ~\dot= ~ c = (vk_s, vk_d, \sigma) \wedge \verify{vk_s}{c}{\sigma}
I think so.  I was just wondering what was the most normal symbol for this. There's also `:=` and `≡` (\equiv).

2018-10-05 14:33 UTC, JaredCorduan commented on specs/ledger/latex/simple-ledger-spec.tex
> +    {\ldelegates{\Gamma; c}{\var{vk_s}}{\var{vk_d}}}
elsewhere we were using union override for this kind of thing.

2018-10-05 15:01 UTC, dnadales commented on specs/ledger/latex/simple-ledger-spec.tex
> +    {\ldelegates{\Gamma; c}{\var{vk_s}}{\var{vk_d}}}
> Let's have the delegation transition defined somewhere.

Isn't the delegation transition what I'm defining here?


> elsewhere we were using union override for this kind of thing.

True. So an alternative formulation would be sth like:

![image](https://user-images.githubusercontent.com/175315/46543051-3a2b6a80-c8c0-11e8-9e15-c61d69e157a1.png)

Does that make more sense?

2018-10-05 15:03 UTC, dnadales commented on specs/ledger/latex/simple-ledger-spec.tex
> +    {\ldelegates{\Gamma; c}{\var{vk_s}}{\var{vk_d}}}
I don't know how we would write a rule in the alternative formulation that says that if a key is not delegated, then it is in the delegation map. This would require us to know the set of keys, or have some sort of "bootstrap" delegation map (which will contain the genesis keys).

2018-10-05 18:02 UTC, JaredCorduan commented on specs/ledger/latex/simple-ledger-spec.tex
> +    & \delegates{c}{vk_s}{vk_d} ~\dot= ~ c = (vk_s, vk_d, \sigma) \wedge \verify{vk_s}{c}{\sigma}
makes total sense!  I'm used to other notations for this, but looking at wikipedia `\doteq` looks to be normal as well.  also, sorry for the typo above, I meant to write "definitional equality".

2018-10-08 12:15 UTC, nc6 commented on specs/ledger/latex/simple-ledger-spec.tex
> +    {\ldelegates{\Gamma; c}{\var{vk_s}}{\var{vk_d}}}
@dnadales As per https://github.com/input-output-hk/cardano-chain/pull/12/files#diff-4c9378c26ca5843fc1cb0764ce515451R201, you have these prefigured for utxo transitions, but not for TxWits or delegation. I would like these to be consistent :-)

2018-10-08 12:15 UTC, nc6 commented on specs/ledger/latex/simple-ledger-spec.tex
> +    & \delegates{c}{vk_s}{vk_d} ~\dot= ~ c = (vk_s, vk_d, \sigma) \wedge \verify{vk_s}{c}{\sigma}
Yeah, I would be more used to `:=` here

2018-10-08 12:20 UTC, dnadales commented on specs/ledger/latex/simple-ledger-spec.tex
> +    & \delegates{c}{vk_s}{vk_d} ~\dot= ~ c = (vk_s, vk_d, \sigma) \wedge \verify{vk_s}{c}{\sigma}
I'm fine with both. So do I change `\dot =` to `:=` (the latter makes me think of assignments in Pascal :D)

2018-10-08 14:21 UTC, JaredCorduan commented on specs/ledger/latex/simple-ledger-spec.tex
> +    & \delegates{c}{vk_s}{vk_d} ~\dot= ~ c = (vk_s, vk_d, \sigma) \wedge \verify{vk_s}{c}{\sigma}
oh, there's also good old `def` above the `=` sign.

2018-10-08 16:52 UTC, dnadales commented
@nc6 @JaredCorduan I just pushed a simplified (and now hopefully correct) version of the delegation rules. Could you check if everything makes sense now so that I can merge this, and move on?

2018-10-09 14:27 UTC, nc6 approved these changes

2018-10-09 14:27 UTC, nc6 commented on specs/ledger/latex/simple-ledger-spec.tex
> +\end{figure}
Rather strange to have this preceding the definitions for delegation.

2018-10-09 14:37 UTC, merged