STS Systems for delegation
input-output-hk/cardano-ledger-byron pull request #215
Opened 2018-12-11 23:24 UTC by nc6

This can be reviewed commit by commit. The first two commits are related to a rewrite of the STS system (and I will open a separate PR for them).

Most of the work here is in the final commit, which adds delegation system types. I still need to add delegation interface types.

2018-12-12 08:20 UTC, dnadales commented on specs/semantics/hs/src/Control/State/Transition.hs
> +import Control.Monad.Free.Church
Maybe import these (`Lens` and `Church`) qualified, so that we know where `F` comes from :)

2018-12-12 11:42 UTC, nc6 commented
#216 should be merged first.

2018-12-12 13:19 UTC, mdimjasevic requested changes
Can you please rebase on top of the current `master`? It looks to me like you haven't done so yet.

2018-12-12 15:17 UTC, nc6 commented
@mdimjasevic Done, although bors would have handled that.

2018-12-13 08:06 UTC, mdimjasevic commented
> @mdimjasevic Done, although bors would have handled that.

I know, but it removes things from the PR that are already in the target branch, which makes reviewing a lot easier.

2018-12-13 10:40 UTC, mdimjasevic approved these changes

2018-12-13 10:40 UTC, mdimjasevic commented on specs/ledger/hs/src/delegation/Ledger/Delegation.hs
> +            return dss'
I haven't thought about this much, but I just wanted to check if you meant to return `dss''` (double prime) by chance. If not, I'd suggest not using a name for that last binding in this `do` block.

2018-12-13 10:40 UTC, mdimjasevic commented on specs/ledger/hs/src/delegation/Ledger/Delegation.hs
> +  initialRules = []
Shouldn't there be at least one initial rule? There has to be an initial state. I am not completely sure about this, but I guess somewhere an initial state has to be created, based on the genesis block's verification keys. Am I right? I envisioned it would happen in a function like this: https://github.com/input-output-hk/cardano-chain/blob/mdimjasevic/193-tying-blockchain-ledger/specs/chain/hs/src/Delegation/Interface.hs#L40

2018-12-13 10:41 UTC, mdimjasevic commented
bors try

2018-12-13 10:45 UTC, nc6 commented on specs/ledger/hs/src/delegation/Ledger/Delegation.hs
> +  initialRules = []
At the moment I'm just reflecting the LaTeX spec. But yes, I wonder also whether this is missing.

2018-12-13 10:46 UTC, nc6 commented
bors r+

2018-12-13 10:49 UTC, merged