Mdimjasevic/193 tying blockchain ledger
input-output-hk/cardano-ledger-byron pull request #221
Opened 2018-12-14 14:20 UTC by mdimjasevic

This patch ties together the blockchain layer and the ledger layer specifications via the delegation interface.

This closes issue #193.

2018-12-14 14:20 UTC, mdimjasevic commented
bors try

2018-12-14 15:36 UTC, nc6 requested changes
Few things that need changing, and a few questions I'd like to clarify!

2018-12-14 15:36 UTC, nc6 commented on specs/chain/hs/src/Chain/Blockchain.hs
> +  , bcEnvDIEnv :: DSEnv
Might want to use the `DIEnv` alias here, just in case things change

2018-12-14 15:36 UTC, nc6 commented on specs/chain/hs/src/Delegation/Interface.hs
> +delegates :: DIState -> Map.Map VKeyGen VKey
Better to remove this function, it just adds unnecessary indirection.

2018-12-14 15:36 UTC, nc6 commented on specs/chain/hs/src/Delegation/Interface.hs
> +initDIState = initDIStateFromKeys initVKeys
The keys are probably in the environment, aren't they?

2018-12-14 15:36 UTC, nc6 commented on specs/chain/hs/src/Delegation/Interface.hs
> +maybeMapKeyForValue :: (Eq a, Ord k) => a -> Map.Map k a -> Maybe k
Reviewing this on a call, so don't have the spec up in front of me. But this seems a slightly weird thing to do - can you point to the section of the spec where this is done? We should make sure that this is reasonable.

2018-12-17 10:47 UTC, mdimjasevic commented on specs/chain/hs/src/Delegation/Interface.hs
> +delegates :: DIState -> Map.Map VKeyGen VKey
Done.

2018-12-17 10:47 UTC, mdimjasevic commented on specs/chain/hs/src/Chain/Blockchain.hs
> +  , bcEnvDIEnv :: DSEnv
Done

2018-12-17 10:52 UTC, mdimjasevic commented on specs/chain/hs/src/Delegation/Interface.hs
> +maybeMapKeyForValue :: (Eq a, Ord k) => a -> Map.Map k a -> Maybe k
This simply follows from the ledger spec that @dnadales wrote. Take a look at `DState` (as you implemented it, and you said you simply followed the spec) and its delegation map. I did ask for the keys and values to be swapped, i.e., to make it a mapping from delegatee keys to delegator keys, but no one reacted to that. Hence this weird function you're asking about, Nicholas.

2018-12-17 11:00 UTC, mdimjasevic commented on specs/chain/hs/src/Delegation/Interface.hs
> +initDIState = initDIStateFromKeys initVKeys
The initial keys are in the genesis block, which the ledger layer is not aware of. Hence it needs to fetch that piece of information from the blockchain layer. Is that the same as the environment?

2018-12-17 13:40 UTC, nc6 commented on specs/chain/hs/src/Delegation/Interface.hs
> +maybeMapKeyForValue :: (Eq a, Ord k) => a -> Map.Map k a -> Maybe k
Fair enough

2018-12-17 13:58 UTC, nc6 commented
@mdimjasevic You've marked things as done but don't seem to have pushed the corresponding changes?

2018-12-17 14:27 UTC, nc6 approved these changes

2018-12-17 14:28 UTC, nc6 commented
bors r+

2018-12-17 14:57 UTC, mdimjasevic commented
> @mdimjasevic You've marked things as done but don't seem to have pushed the corresponding changes?

My apologies for that. I kept them local while waiting to settle down the remaining issues and to push it at once. They're available now.

2018-12-17 15:21 UTC, mdimjasevic commented
bors r+

2018-12-17 15:44 UTC, nc6 commented
bors r+

2018-12-17 16:37 UTC, nc6 commented
bors retry

2018-12-17 17:06 UTC, merged

2018-12-18 07:25 UTC, mdimjasevic commented
> bors retry

Thank you for baby-sitting this silly issue that we currently have with builds, @nc6!