[WIP] [223] Add initial delegation rules
input-output-hk/cardano-ledger-byron pull request #228
Opened 2018-12-21 14:30 UTC by mdimjasevic

This work-in-progress PR adds initial delegation rules. I'm guessing they are not correct; I added them just to start a discussion on what are appropriate values here. @nc6, @dnadales, your comments would be appreciated. @dnadales, if you'll need this during the Christmas break, feel free to take over as I'll be away.

TODO: make sure corresponding rules are in the LaTeX ledger specification.

This patch closes issue #223.

2018-12-21 17:09 UTC, nc6 reviewed
Changes look good in general, have marked a couple of areas which could be changed.

2018-12-21 17:09 UTC, nc6 commented on specs/chain/hs/src/Chain/Blockchain.hs
> +import Data.Maybe (isJust, fromJust, listToMaybe)
Not needed?

2018-12-21 17:09 UTC, nc6 commented on specs/ledger/hs/src/Ledger/Delegation.hs
> +                       }
Yep

2018-12-21 17:09 UTC, nc6 commented on specs/chain/hs/src/Delegation/Interface.hs
> +initDIStateFromKeys keys = DIState
This whole module should not be needed now, I think?

2018-12-26 16:33 UTC, dnadales commented
One question for ourselves: do we want to restrict the initial environment as well? For instance, in the case of the delegation environment, if there are no allowed delegators, then the generators will not be able to generate any trace (since a delegation certificate requires at least one allowed delegator). What to do in this case?

2019-01-02 10:41 UTC, mdimjasevic commented on specs/chain/hs/src/Chain/Blockchain.hs
> +import Data.Maybe (isJust, fromJust, listToMaybe)
Are you referring to all the three imported functions? Each of them is used in the module.

2019-01-02 12:38 UTC, mdimjasevic commented on specs/ledger/hs/src/Ledger/Delegation.hs
> +                       }
Are you saying this is a good implementation?

2019-01-02 12:39 UTC, mdimjasevic commented on specs/chain/hs/src/Delegation/Interface.hs
> +initDIStateFromKeys keys = DIState
I believe you're right. I removed the module.

2019-01-02 12:40 UTC, mdimjasevic commented
> One question for ourselves: do we want to restrict the initial environment as well? For instance, in the case of the delegation environment, if there are no allowed delegators, then the generators will not be able to generate any trace (since a delegation certificate requires at least one allowed delegator). What to do in this case?

Can you please provide some further explanation? I am not sure I understand what in specific you're talking about.

2019-01-02 13:30 UTC, dnadales commented
> Can you please provide some further explanation? I am not sure I understand what in specific you're talking about.

The initial rules could restrict the environment. I gave an example of this above. Consider if the set of valid delegators is empty. Do we want that?

2019-01-02 13:47 UTC, mdimjasevic commented
> The initial rules could restrict the environment. I gave an example of this above. Consider if the set of valid delegators is empty. Do we want that?

How about using the [Data.NonEmpty.Map](http://hackage.haskell.org/package/non-empty-0.3.0.1/docs/Data-NonEmpty-Map.html) module?

2019-01-02 14:05 UTC, dnadales commented
> How about using the Data.NonEmpty.Map module?

Sure. But I was aiming at what do we want in the specs :)

2019-01-03 06:14 UTC, dnadales commented on specs/ledger/hs/src/Ledger/Delegation.hs
> +  initialRules = [ do
It seems the initial state rule for the delegation interface doesn't use any of the other initial rules  (in `SDELEG`(`S`) or `ADELEG`(`S`)), so the question is: do we need the other initial rules? Can't we just specify the initial rules for `DELEG`?

I'm just trying to remove what we might not need.

2019-01-03 11:39 UTC, mdimjasevic commented on specs/ledger/hs/src/Ledger/Delegation.hs
> +  initialRules = [ do
To admit, I wasn't following closely how are all `*State` states related, mostly because, as I mentioned it earlier, I find their names rather confusing and hard to read. Anyhow, now by looking at it, am I right to say that `DIState` is actually made of a `DSState` and a `DState`? If so, I'd suggest to reflect that in the `DIState`'s data constructor and then we can update these initial states accordingly.

2019-01-03 11:41 UTC, dnadales commented on specs/ledger/hs/src/Ledger/Delegation.hs
> +  initialRules = [ do
Yes, that could also work.

2019-01-15 16:14 UTC, nc6 commented
Why the last change? `cs-blockchain` depends on `cs-ledger`, so what's wrong with having the relevant types there?

2019-01-16 07:20 UTC, mdimjasevic commented
> Why the last change? `cs-blockchain` depends on `cs-ledger`, so what's wrong with having the relevant types there?

This is to enable actual running (e.g., testing) eventually. With the way code was organised, there would be a circular dependency because keys from the genesis block are needed for the initial state of the `ADELEG` STS, yet as you said `cs-blockchain` already depends on `cs-ledger`).

2019-01-16 10:21 UTC, mdimjasevic commented
> > Why the last change? `cs-blockchain` depends on `cs-ledger`, so what's wrong with having the relevant types there?
> 
> This is to enable actual running (e.g., testing) eventually. With the way code was organised, there would be a circular dependency because keys from the genesis block are needed for the initial state of the `ADELEG` STS, yet as you said `cs-blockchain` already depends on `cs-ledger`).

@nc6 , do you think this is not needed? On a second thought, I guess so long as no attempt to actually run `cs-ledger`'s STSes is made from within `cs-ledger`, there is no need for this separation into `cs-core`. If you think we won't ever run it from there, I'll undo this separation.

2019-01-16 11:25 UTC, mdimjasevic commented
@dnadales , @nc6: I'm done with implementing initial delegation rules. Please review again.

2019-01-16 11:36 UTC, ruhatch reviewed
This seems sensible, but I want more eyes on it as I'm not as familiar as others. The cs-core package is still here, but you said in a comment above you wanted to remove it, is that still the case?

2019-01-16 11:53 UTC, mdimjasevic commented
> This seems sensible, but I want more eyes on it as I'm not as familiar as others. The cs-core package is still here, but you said in a comment above you wanted to remove it, is that still the case?

I'm waiting on Nicholas to comment, as he had concerns with introducing `cs-core`.

2019-01-16 11:56 UTC, nc6 requested changes
I would like to revert the cs-core stuff; I don't feel it adds anything and it means one more place people have to look. Other than that, LGTM!

2019-01-16 12:17 UTC, mdimjasevic commented
> I would like to revert the cs-core stuff; I don't feel it adds anything and it means one more place people have to look. Other than that, LGTM!

Ok, I removed it!

2019-01-16 12:33 UTC, nc6 approved these changes

2019-01-16 12:44 UTC, mdimjasevic commented
bors r+

2019-01-16 13:00 UTC, merged