Add a valid delegation signals generator
input-output-hk/cardano-ledger-byron pull request #229
Opened 2018-12-27 17:12 UTC by dnadales

- Add a generator for delegation traces. In a nutshell, a trace is a sequence of signal-and-ensuing-state pairs.
- Add two property based tests which check properties on the generated traces: delegation certificates in a trace are applied as expected, and duplicated scheduled delegations are rejected.
- Add two unit tests for the delegation rules: one for delegation activation, and other for delegation scheduling. These simple unit test proved to be useful to detect errors in the coding of the delegation rules.
- Add the concept of non-trivial signal, which allows to detect when errors are introduced in the encoding of the delegation rules. Otherwise, only trivial signals would be produced, and the error would remain undetected.
- Set RTS limits for the tests.
- Remove `brittany` checks on `specs` from CI: in some cases the automatic applied formatting did not produce more readable code, so I don't think we can benefit from it.
- Introduce a simple DSL for specifying expectations on transition system traces.
- Compiler warnings will be considered errors. Existing warnings in `specs` were removed.
- Remove the `Makefile` from `specs/ledger/hs`.

2019-01-02 09:13 UTC, mgudemann commented on specs/ledger/hs/src/Ledger/Core.hs
> +newtype VKeyGen = VKeyGen VKey
I would prefer making `Gen` unambiguous here, e.g. `VKeyGenesis` I initially read it as abbreviation for generator.

2019-01-02 09:13 UTC, mgudemann commented on specs/ledger/hs/src/Ledger/Core/Generator.hs
> +natGen = integral (linear 0 100)
As I have been bitten by this, maybe parameterize this for min/max and make it a choice between linear and exponential choice?

2019-01-02 09:13 UTC, mgudemann commented on specs/ledger/hs/src/Ledger/Delegation.hs
> +        List.notElem
where is the negation coming from, was this wrong before ? Above it was a change from `not $ Set.elem ... ` to `Set.notElem ...`

2019-01-02 09:13 UTC, mgudemann commented on specs/ledger/hs/src/Ledger/Delegation.hs
> +-- and the generator will have to retry.
should this Note be merged with the above comment?

2019-01-02 09:13 UTC, mgudemann commented on specs/ledger/hs/test/Ledger/Delegation/Examples.hs
> +
remove newline here ?

2019-01-02 09:13 UTC, mgudemann commented on specs/semantics/hs/src/Control/State/Transition/Trace.hs
> +--
Maybe add in this description that the sequence is reversed, i.e., the initial state is the last.

2019-01-02 14:56 UTC, mdimjasevic submitted a review, later dismissed
Generators should be put under the `test` directory, and not `src`.

2019-01-02 14:56 UTC, mdimjasevic commented on specs/ledger/hs/cs-ledger.cabal
> +                     , Ledger.Core.Generator
Why is not this generator module part of testing?

2019-01-02 14:56 UTC, mdimjasevic commented on specs/ledger/hs/src/Ledger/Delegation.hs
> +        let slots = filter ((<= (env ^. slot)) . fst) $ sds ^. scheduledDelegations
Was this a buggy implementation, hence the change to `<=`?

2019-01-02 14:56 UTC, mdimjasevic commented on specs/ledger/hs/src/Ledger/Core/Generator.hs
> +vkgGen = VKeyGen <$> vkGen
Can you please use more distinguishing names? At first I thought this was a circular definition where `vkgGen` depends on itself. It took mi minutes to spot it is defined via `vkGen` instead. Descriptions would be helpful in comments too.

2019-01-02 14:56 UTC, mdimjasevic commented on specs/ledger/hs/src/Ledger/Delegation.hs
> +               , _depoch = epo
Shouldn't you make the generated epoch somehow related to the epoch in the environment?

2019-01-03 11:19 UTC, mdimjasevic commented on specs/ledger/hs/test/Ledger/Delegation/Properties.hs
> +data DBlock
What's the motivation behind introducing a new type for blocks? Are there limitations or obstacles in using the one defined in `cs-blockchain`?

2019-01-03 11:26 UTC, mdimjasevic commented on specs/semantics/hs/src/Control/State/Transition/Trace.hs
> +--
Overall, this is an enormous PR. There is an "infrastructure" part like the `Generator` and `Trace` modules, there are properties, there are examples, there are actual HedheHog generators, changes to the existing STS library and what not. Please split it and sequence it into smaller self-contained chunks.

2019-01-03 12:07 UTC, nc6 requested changes
Done a first pass review and left a few comments in particular places. I think in general this looks great. My main concern is again around the conception of initial rules and states - happy to either chat more about this in Slack or in Berlin next week!

2019-01-03 12:07 UTC, nc6 commented on specs/ledger/hs/cs-ledger.cabal
> +                     , Ledger.Core.Generator
This whole library really pertains to testing - we are defining the spec in order to test the real implementation. And we will want to expose these generators to downstream libraries that wish to use them - for example, we have discussed having a CLI utility to generate chains to use in testing the Rust implementation.

So having this in the normal library is definitely correct :-)

2019-01-03 12:07 UTC, nc6 commented on specs/ledger/hs/cs-ledger.cabal
> +               -- The 50 megabytes heap bound was determined ad-hoc.
It would be useful to record here the purpose of this bound

2019-01-03 12:07 UTC, nc6 commented on specs/ledger/hs/src/Ledger/Core/Generator.hs
> +natGen = integral (linear 0 100)
I wonder whether we would be better inlining this in `epochGen`, `slotGen` etc. I feel that the idea of "generator for natural numbers" is unlikely to be semantically useful.

2019-01-03 12:07 UTC, nc6 commented on specs/ledger/hs/src/Ledger/Delegation.hs
> +import Ledger.Core.Generator (epochGen, slotCountGen, slotGen, vkGen, vkgGen)
I must admit to being a sceptic about the idea of importing everything explicitly like this! I feel it results in a lot of boilerplate and a lot of churn when things change. But each to their own!

2019-01-03 12:07 UTC, nc6 commented on specs/ledger/hs/src/Ledger/Delegation.hs
> +        List.notElem
I think it was wrong before, which Damian helpfully discovered when testing!

2019-01-03 12:07 UTC, nc6 commented on specs/ledger/hs/src/Ledger/Delegation.hs
> +initialDIState :: DIState
Would it make more sense to have this as an initial rule?

2019-01-03 12:07 UTC, nc6 commented on specs/semantics/hs/src/Control/State/Transition.hs
> +newtype IRC sts = IRC (Environment sts, State sts)
I don't understand this change. What can it mean to have an existing state, given this is an initial rule? And how would it be used in any case?

2019-01-03 12:07 UTC, nc6 commented on specs/semantics/hs/src/Control/State/Transition.hs
> +ctxState STransition (TRC (_, st, _)) = st
As above, this seems wrong.

2019-01-03 12:07 UTC, nc6 commented on specs/semantics/hs/src/Control/State/Transition.hs
> +  headOrState [] = (ctxState rTypeRep ctx, [])
This definitely seems wrong. If this fails at the initial rule, there is no state to fall back on. So an error is really the only option. And this case is only called if there are actually no rules to apply.

2019-01-03 12:07 UTC, nc6 commented on specs/semantics/hs/src/Control/State/Transition/Generator.hs
> +  initStGen :: Environment s -> Gen (State s)
Not seeing the point of this. Why does this not simply arise from applying an initial rule against the generated environment?

2019-01-03 12:07 UTC, nc6 commented on specs/semantics/hs/src/Control/State/Transition/Trace.hs
> +-- This module also includes a minimal DEL to specify expectations on traces.
What's a DEL?

2019-01-04 08:34 UTC, dnadales commented on specs/ledger/hs/cs-ledger.cabal
> +               -- The 50 megabytes heap bound was determined ad-hoc.
:+1: 

What about:

```
               -- We set a bound here so that we're alerted of potential space
               -- leaks in our generators (or test) code.
```

2019-01-04 08:36 UTC, dnadales commented on specs/ledger/hs/src/Ledger/Core.hs
> +newtype VKeyGen = VKeyGen VKey
Good one, I'm gonna change that.

2019-01-04 10:51 UTC, dnadales commented on specs/ledger/hs/src/Ledger/Core/Generator.hs
> +natGen = integral (linear 0 100)
Note that `natGen` is only used in this module (and thus not exported). I was not sure what would be good arbitrary ranges for slots, epochs, keys, etc. So I just used the same generator, `natGen`.

I would say, as we find that `integral (linear 0 100)` is not a good generator for any of the type wappers around `Natural` (e.g. `Epoch`, we could inline the generator and tweak the parameters, or replace it by `exponential` for instance). Does that make sense? @mgudemann @nc6 If it doesn't, do you have any concrete suggestion about what would be a good approach here?

2019-01-04 10:56 UTC, dnadales commented on specs/ledger/hs/src/Ledger/Delegation.hs
> +import Ledger.Core.Generator (epochGen, slotCountGen, slotGen, vkGen, vkgGen)
Yes, that is a big downside. The problem is that when reading code, I usually find myself looking for the place at which a symbol is defined, and if it is imported I don't know where it is imported from. GNU tags alleviate this problem somehow, but it doesn't work for symbols imported from external libraries.

I think the ideal solution would be to have proper tag navigation support in Haskell (maybe it exists already and I don't know), but in its absence I'd rather go for the more bureaucratic approach for the sake of future maintainers.

However I'm wondering how do you deal with this situation, maybe if you have a good approach for looking up symbols we might just document that and have implicit imports only.

2019-01-04 11:05 UTC, dnadales commented on specs/ledger/hs/src/Ledger/Delegation.hs
> +initialDIState :: DIState
Certainly! Let's discuss how to go about this!

From the top of my head this would correspond to an inital rule of the form:

```
dms = K \mapsto K
dws = \emptyset
sds = \epsilon
eks = \emptyset
------------------
(dms
 dws
 sds
 eks)
```

But we also have to contemplate cases with initial rules where multiple initial states are possible, e.g.:

```
0 < n
-------
( n )
```

2019-01-04 11:08 UTC, dnadales commented on specs/ledger/hs/src/Ledger/Delegation.hs
> +        List.notElem
Before, `List.elem` was actually computing whether a delegation was scheduled, we wanted to know whether it wasn't scheduled instead. And indeed, testing helped us to discover this :)

2019-01-04 11:08 UTC, dnadales commented on specs/ledger/hs/src/Ledger/Delegation.hs
> +        let slots = filter ((<= (env ^. slot)) . fst) $ sds ^. scheduledDelegations
Yup, we discovered this when testing.

2019-01-04 11:09 UTC, dnadales commented on specs/ledger/hs/src/Ledger/Delegation.hs
> +               , _depoch = epo
Why?

2019-01-04 11:10 UTC, dnadales commented on specs/ledger/hs/src/Ledger/Delegation.hs
> +-- and the generator will have to retry.
I was thinking the note has more to do with the implementation detail, and I didn't want it showing as part of the documentation. Does it make sense?

2019-01-04 11:15 UTC, dnadales commented on specs/ledger/hs/test/Ledger/Delegation/Properties.hs
> +data DBlock
These type of blocks is used to tests the delegation rules, using the transition system defined below. I didn't need the full blown `cs-blockchain` here. Besides this would introduce a circular dependency.

2019-01-04 11:17 UTC, dnadales commented on specs/semantics/hs/small-steps.cabal
> +               "-with-rtsopts=-K1m -M50m"
I think I did something stupid here. RTS options don't have effect on libraries :/

2019-01-04 11:24 UTC, dnadales commented on specs/semantics/hs/src/Control/State/Transition/Trace.hs
> +--
The original idea was to use the progressive gen's in #127 . However, as we discussed with @nc6 I couldn't use it to get generators for delegation, so all the infrastructure was needed. The work on this was done during the christmas break, so it made no sense to split this into smaller PR's since I'd have to wait till after the break.

I'll try to make smaller PR's in the future, but for this one I guess a workaround would be to consider N files a day, and pretend they come from smaller PR's :man_shrugging: :)

2019-01-04 11:27 UTC, dnadales commented on specs/semantics/hs/src/Control/State/Transition/Trace.hs
> +--
My idea was not to give any information in the documentation about the order in which the signals-state pairs are added to the list. Since this field is not exported, the users of this module don't have to worry about this detail. When the trace needs to be extracted as a list, the trace order has to be given explicitly. Does this sound reasonable?

2019-01-04 11:28 UTC, dnadales commented on specs/semantics/hs/src/Control/State/Transition/Trace.hs
> +-- This module also includes a minimal DEL to specify expectations on traces.
What results from a typo in `DSL` :P Sorry about that. Changing it now.

2019-01-04 11:39 UTC, mdimjasevic commented on specs/ledger/hs/src/Ledger/Delegation.hs
> +               , _depoch = epo
At the moment, the generated epoch is completely unrelated to the epoch in the environment. Will not this lead to a lot of generated test cases being uninteresting in the sense that they will not lead to a next valid state?

2019-01-04 11:53 UTC, dnadales commented on specs/semantics/hs/src/Control/State/Transition/Generator.hs
> +  initStGen :: Environment s -> Gen (State s)
My idea was that one should be able to generate initial states for rules that specify more than one initial state. For instance:

```
0 <  n
--------
( n )
```

2019-01-04 11:54 UTC, dnadales commented on specs/semantics/hs/src/Control/State/Transition.hs
> +  headOrState [] = (ctxState rTypeRep ctx, [])
Yeah, might be. This was my clumsy workaround for avoiding `error`s in cases in which the initial rules where empty. I'd like to avoid the use of `error` if possible.

2019-01-04 13:23 UTC, dnadales commented on specs/semantics/hs/src/Control/State/Transition.hs
> -  successOrFirstFailure xs = fromMaybe (head xs) $ find (not . null . snd) xs
TODO: replace `head` by `headWithError` which states what is the error we got.

2019-01-04 13:24 UTC, dnadales commented on specs/semantics/hs/src/Control/State/Transition/Generator.hs
> +  initStGen :: Environment s -> Gen (State s)
Now I see what you meant. So I'm gonna change.

2019-01-04 14:43 UTC, dnadales commented on specs/ledger/hs/src/Ledger/Delegation.hs
> +               , _depoch = epo
Indeed, good point. I'll change the generator so that a random increment is added to the epoch in the environment.

2019-01-04 14:55 UTC, dnadales commented on specs/semantics/hs/src/Control/State/Transition.hs
> +newtype IRC sts = IRC (Environment sts, State sts)
I reverted this back, as we discussed today.

2019-01-04 14:56 UTC, dnadales commented on specs/ledger/hs/src/Ledger/Delegation.hs
> +initialDIState :: DIState
Alright, I just incorporated this initial state in an initial rule.

2019-01-04 15:12 UTC, dnadales commented
Thank you @mdimjasevic @mgudemann and @nc6 for taking the time to review this. I tried to address your concerns as well as I could. Let me know if you approve this version or whether there are other things I should address.

@mdimjasevic note that I added an initial rule for `DELEG` to be able the interpret the generators in the way we discussed today, however whatever rules you're writing in your PR should take precedence, so I hope this is not a problem.

2019-01-04 15:30 UTC, mgudemann commented on specs/ledger/hs/src/Ledger/Core/Generator.hs
> +natGen = integral (linear 0 100)
I currently have this
```
-- | Generator for a natural number between 'lower' and 'upper'.
genNatural :: Natural -> Natural -> Gen Natural
genNatural lower upper = Gen.integral $ Range.linear lower upper
```
But I'd suggest a choice like
```
genNatural lower upper = Gen.choice [ Gen.integral $ Range.linear lower upper
                                                            , Gen.exponential $ Range.linear lower upper]
```

2019-01-04 15:32 UTC, mgudemann commented on specs/ledger/hs/src/Ledger/Core/Generator.hs
> +natGen = integral (linear 0 100)
that isn't perfect, the suggestion at the training was to generate lots of "low" values, lots of "high" values and some in between

2019-01-04 15:35 UTC, mgudemann approved these changes

2019-01-04 15:38 UTC, nc6 approved these changes

2019-01-04 15:38 UTC, dnadales commented on specs/ledger/hs/src/Ledger/Core/Generator.hs
> +natGen = integral (linear 0 100)
Oh, I see. Right now I just removed `natGen`, and inlined the `Gen.integral` whenever I needed them. 

@nc6 do you think having a generator like the one @mgudemann suggests would make sense at this stage?

2019-01-07 08:10 UTC, mdimjasevic commented
Now that you changed `VKeyGen` to `VKeyGenesis` in the code, do you want to update it in the specs too? I know I used `VKeyGen` in the blockchain spec.

2019-01-07 11:03 UTC, mdimjasevic commented
I wasn't able to decipher how Github works with reviews, but I guess that my requested changes review isn't technically blocking you from proceeding with merging to `master`.

2019-01-08 08:11 UTC, dnadales commented
bors try

2019-01-08 08:11 UTC, dnadales commented
> Now that you changed VKeyGen to VKeyGenesis in the code, do you want to update it in the specs too? I know I used VKeyGen in the blockchain spec.

Sure.

2019-01-08 08:24 UTC, dnadales commented
bors r+

2019-01-08 09:39 UTC, dnadales commented
Bors r+

2019-01-08 09:46 UTC, merged