[DEVOPS-1214] Nix-toolification of cardano-chain
input-output-hk/cardano-ledger-byron pull request #246
Opened 2019-01-18 13:15 UTC by angerman

This adds the nix-tools infra to cardano-chain.
Cross compilation is blocked on additional support
in iohk-nix, which will come in due course.

2019-01-22 09:52 UTC, cleverca22 approved these changes

2019-01-22 15:16 UTC, nc6 commented
This looks reasonable, but also makes the nix infrastructure in this repo look a lot more complicated. Can we include with this PR appropriate instructions for what one needs to do for such things as:

- Adding a new Haskell specification
- Adding a new LaTeX specificiation
- Changing the dependencies of one of the packages

2019-01-22 15:16 UTC, nc6 requested changes
Documentation as per previous comment?

2019-01-23 12:26 UTC, angerman commented
@nc6 We've moved the default and release nix templates into iohk-nix, which should make this easier to read (I hope).

In general you will be able to use `stack-to-nix` (instructions will follow) to turn your regular `stack.yaml` file into the necessary `nix/pkgs.nix` file.  That is also where you could do custom
configurations of haskell packages should they need any configuration beyond what stack
already sets.

You should also see the custom packages section where the LaTeX specs are in.  Let me know any other thoughts you have.  I'd be happy make this work for you as good as possible.

2019-01-23 13:41 UTC, angerman commented on nix/pkgs.nix
> +  inherit (import ./haskell-hackage-stackage.nix { inherit pkgs; }) haskell hackage stackage;
@rvl, I think these should become arguments, and be feed in from iohk-nix. What do you think? That would remove the need to have a `haskell-hackage-stackage.nix` expression per repo. And we rally don't want to have to bump them across projects do we? Rather bump `iohk-nix` as needed.

2019-01-23 13:42 UTC, angerman commented on nix/pkgs.nix
> +      {
@rvl, @jbgi: I wonder if we could feed these in as cross patches from iohk-nix as well. it seems stupid if we have to replicate all patches in each and every repo.  Ideally we'd even apply the patches transparently with the project having to worry about it :(

2019-02-04 15:49 UTC, angerman commented
This currently depends on input-output-hk/iohk-nix#30. Once merged, this should be good to go.

2019-02-12 12:43 UTC, nc6 approved these changes

2019-02-12 13:34 UTC, angerman commented
bors try

2019-02-12 13:35 UTC, angerman commented
@nc6 the stack-rebuild build kite job failed. All I did was make a small change to the stack.yaml file to contain all targets:
https://github.com/input-output-hk/cardano-chain/pull/246/files#diff-fafd0cdcd559a7b124cc61c29413fb54

Any idea?

2019-02-12 14:41 UTC, nc6 commented
@angerman Looks like we're trying to pass an option that doesn't exist to the chain tests. But we're about to prune the specs from the repo (and move them to fm-ledger-rules), so I think we should just remove this change from the stack.yaml file and go ahead with this anyway.

2019-02-12 14:42 UTC, nc6 commented
bors try

2019-02-12 14:48 UTC, angerman commented
@nc6 Alright. I'll take care of it and merge tomorrow SGT then.

2019-02-12 14:50 UTC, angerman commented
@nc6 one more thing. Do we need to keep the stack build job if we have hydra?

2019-02-12 14:55 UTC, nc6 commented
You mean the buildkite job? Quite possibly not, but let's deal with that in a separate PR.

2019-02-12 15:26 UTC, nc6 commented
bors r+

2019-02-12 16:07 UTC, merged