[#222] Update `ProtocolMagic` to include `RequiresNetworkMagic`
input-output-hk/cardano-ledger-byron pull request #250
Opened 2019-01-21 18:02 UTC by Jimbo4350

Linked issue: https://iohk.myjetbrains.com/youtrack/issue/CO-354
Closes #222

2019-01-22 09:49 UTC, ruhatch requested changes
Looks good! Glad it wasn't as extensive as the `cardano-sl` implementation!

Just a few small changes to be made :)

2019-01-22 09:49 UTC, ruhatch commented on crypto/src/Cardano/Crypto/ProtocolMagic.hs
> +import Prelude (lookup, String)
Please import these from their modules, `Data.List`, `Data.String`, respectively I believe

2019-01-22 09:49 UTC, ruhatch commented on crypto/src/Cardano/Crypto/ProtocolMagic.hs
> +    (JSNum n) ->
I think these brackets are redundant!

2019-01-22 09:49 UTC, ruhatch commented on crypto/src/Cardano/Crypto/ProtocolMagic.hs
> +    (JSString "RequiresNoMagic") -> pure RequiresNoMagic
And these too

2019-01-22 09:49 UTC, ruhatch commented on crypto/test/Test/Cardano/Crypto/Arbitrary.hs
> +instance Arbitrary ProtocolMagic where
Not sure these will be necessary - try deleting them and recompiling to see if there's any QuickCheck stuff using them

2019-01-22 09:49 UTC, ruhatch commented on crypto/test/Test/Cardano/Crypto/Arbitrary.hs
> +instance Arbitrary ProtocolMagic where
Oh actually, I don't think I finished removing QuickCheck here

2019-01-22 09:49 UTC, ruhatch commented on crypto/test/Test/Cardano/Crypto/Dummy.hs
> +dummyProtocolMagic = ProtocolMagic (ProtocolMagicId 55550001) RequiresMagic
Might as well do:
```suggestion
dummyProtocolMagic = ProtocolMagic dummyProtocolMagicId RequiresMagic
```

2019-01-22 09:49 UTC, ruhatch commented on src/Cardano/Chain/Block/Header.hs
> +      <> encode (unProtocolMagicId $ (headerProtocolMagicId h))
Could be better to `deriving Bi` on `ProtocolMagicId` type using `GeneralizedNewtypeDeriving` so you get the unwrapping for free

2019-01-22 09:49 UTC, ruhatch commented on src/Cardano/Chain/Block/Header.hs
> +        <$> (ProtocolMagicId <$> decode)
And then you could change this too

2019-01-22 09:49 UTC, ruhatch commented on src/Cardano/Chain/Delegation/Validation.hs
> +  validateProxySecretKey (getProtocolMagicId $ configProtocolMagic config) cert
I would define a `configProtocolMagicId :: Config -> ProtocolMagicId` as this is used in a couple of places

2019-01-22 09:49 UTC, ruhatch commented on src/Cardano/Chain/Delegation/Validation.hs
> +  validateProxySecretKey (getProtocolMagicId $ configProtocolMagic config) cert
Define that alongside `Config` of course, not here

2019-01-22 09:49 UTC, ruhatch commented on src/Cardano/Chain/Genesis/Data.hs
> +        , ("protocolMagic", toJSON . unProtocolMagicId.  getProtocolMagicId $ gdProtocolMagic gd)
Didn't we define `getProtocolMagic` in terms of these two?

2019-01-22 18:36 UTC, Jimbo4350 commented on crypto/src/Cardano/Crypto/ProtocolMagic.hs
> +import Prelude (lookup, String)
Forgot I did that!

2019-01-23 10:30 UTC, ruhatch approved these changes
A couple of small changes, then feel free to merge!

2019-01-23 10:30 UTC, ruhatch commented on crypto/src/Cardano/Crypto/ProtocolMagic.hs
> +import Cardano.Binary.Class (Bi)
Can you put two blank lines after imports here?

2019-01-23 10:30 UTC, ruhatch commented on crypto/src/Cardano/Crypto/Signing/Tag.hs
> +  where network = Bi.serialize' (unProtocolMagicId $ protocolMagic)
You should be able to use the `ProtocolMagicId` instance here I think
```suggestion
  where network = Bi.serialize' protocolMagic
```

2019-01-24 18:22 UTC, Jimbo4350 commented
bors r+

2019-01-24 19:11 UTC, Jimbo4350 commented
bors r+

2019-01-24 19:18 UTC, merged