Upgrade cardano-binary to GHC 8.6.3
input-output-hk/cardano-ledger-byron pull request #264
Opened 2019-01-24 14:43 UTC by mdimjasevic

This upgrades `cardano-binary` to GHC 8.6.3.

Closes #263.

2019-01-25 14:10 UTC, ruhatch requested changes

2019-01-25 14:10 UTC, ruhatch commented on binary/stack.yaml
> +  - pretty-show-1.8.2
This won't be necessary once you make the change in `cardano-prelude` :)

2019-01-25 14:50 UTC, mdimjasevic commented on binary/stack.yaml
> +  - pretty-show-1.8.2
@ruhatch: done!

2019-01-25 14:50 UTC, mdimjasevic commented
bors try

2019-01-25 15:03 UTC, mdimjasevic commented
bors retry

2019-01-25 15:06 UTC, avieth commented
Related https://github.com/input-output-hk/cardano-sl/pull/4035

I found that `micro-recursion-schemes` still has a `template-haskell < 2.14` constraint, but `recursion-schemes` latest admits `2.14`

2019-01-28 09:49 UTC, mdimjasevic commented
bors retry

2019-01-28 10:23 UTC, mdimjasevic commented
bors try

2019-01-28 10:24 UTC, mdimjasevic commented
bors retry

2019-01-28 10:25 UTC, mdimjasevic commented
@ruhatch, do you want to take another look now? I addressed the issue with `pretty-show`.

2019-01-28 17:16 UTC, ruhatch approved these changes

2019-01-28 17:16 UTC, ruhatch commented
bors r+

2019-01-29 07:54 UTC, mdimjasevic commented
bors r+

2019-01-29 15:44 UTC, ruhatch commented
bors r+

2019-01-30 11:56 UTC, mdimjasevic commented
bors r+

2019-01-30 12:57 UTC, mdimjasevic commented
bors r+

2019-01-30 13:38 UTC, merged