Upgrade cardano-crypto-wrapper to depend on GHC 8.6.3
input-output-hk/cardano-ledger-byron pull request #267
Opened 2019-01-24 16:26 UTC by mdimjasevic

This upgrades `cardano-crypto-wrapper`'s stack build to GHC 8.6.3.

The `tasty-hedhehog` package had to be declared in a `stack.yaml` file.

Closes #265.

2019-01-25 14:12 UTC, ruhatch requested changes

2019-01-25 14:12 UTC, ruhatch commented on crypto/stack.yaml
> +  - pretty-show-1.8.2
Shouldn't be necessary if you update the snapshot in `cardano-prelude`

2019-01-28 09:21 UTC, mdimjasevic commented on crypto/stack.yaml
> +  - pretty-show-1.8.2
@ruhatch, you're right. I removed this.

2019-01-28 09:39 UTC, mdimjasevic commented
bors try

2019-01-28 09:50 UTC, mdimjasevic commented
@ruhatch, can you make your review approving? Your concern was addressed and bors builds pass now.

2019-01-28 17:17 UTC, ruhatch approved these changes

2019-01-28 17:17 UTC, ruhatch commented
bors r+

2019-01-29 07:55 UTC, mdimjasevic commented
bors r+

2019-01-30 11:58 UTC, mdimjasevic commented
bors r+

2019-01-30 12:11 UTC, mdimjasevic commented
bors r+

2019-01-30 13:38 UTC, merged