[DO NOT MERGE] Add some scaffolding for testing the validator with the generated chains
input-output-hk/cardano-ledger-byron pull request #308
Opened 2019-02-06 21:00 UTC by dnadales

A preliminary PR to get some early feedback.

2019-02-07 09:16 UTC, ruhatch requested changes
Looking good so far!

2019-02-07 09:16 UTC, ruhatch commented on test/Test/Cardano/Chain/Block/Validation/Spec.hs
> +      :: Concrete.ChainValidationState
I guess you could just take the previous hash from the `ChainValidationState` :man_shrugging:

2019-02-07 09:16 UTC, ruhatch commented on test/Test/Cardano/Chain/Block/Validation/Spec.hs
> +        res = foldM interpretAndUpdate initSt $ traceSignals OldestFirst tr
:+1:

2019-02-07 09:16 UTC, ruhatch commented on test/Test/Cardano/Chain/Block/Validation/Spec.hs
> +  -- TODO: remove this duplication - see test/Test/Cardano/Chain/Block/Validation.hs
Did you remove this duplication already with `Utils`?

2019-02-07 09:16 UTC, ruhatch commented on test/Test/Cardano/Chain/Block/Validation/Spec.hs
> +      either (panic . show) (const $ pure ()) res
```suggestion
      void $ evalEither res
```

2019-02-07 09:16 UTC, ruhatch commented on test/Test/Cardano/Chain/Block/Validation/Spec.hs
> +      either (panic . show) (const $ pure ()) res
I think that's more idiomatic for `hedgehog`

2019-02-07 09:16 UTC, ruhatch commented on test/Test/Cardano/Chain/Block/Validation/Spec.hs
> +        initSt = either (panic . show) identity $
I guess you could use `evalEither` here too and then put this in the `do` block. Not sure if that would cause this code to run more times though...

2019-02-07 09:16 UTC, ruhatch commented on test/Test/Cardano/Chain/Common/Utils.hs
> +module Test.Cardano.Chain.Common.Utils
I think `Test.Cardano.Chain.Config` might be a better location

2019-02-07 10:40 UTC, dnadales commented on test/Test/Cardano/Chain/Block/Validation/Spec.hs
> +      :: Concrete.ChainValidationState
Sure, maybe we need to relax the pre-conditions on this function (now called `elaborate` :)).

2019-02-07 10:40 UTC, dnadales commented on test/Test/Cardano/Chain/Block/Validation/Spec.hs
> +  -- TODO: remove this duplication - see test/Test/Cardano/Chain/Block/Validation.hs
Yes. I just forgot to remove the comment :man_facepalming:

2019-02-07 10:45 UTC, dnadales commented on test/Test/Cardano/Chain/Block/Validation/Spec.hs
> +        initSt = either (panic . show) identity $
Yes. I was planing on getting read of this "panic show" pattern, so thanks for pointing me to `evalEither`.

2019-02-07 11:00 UTC, dnadales commented
Thanks for the first batch of reviews @ruhatch !

2019-02-11 14:15 UTC, ruhatch reviewed
Maybe we should add `stack-local.yaml` to the `.gitignore` too :)

2019-02-11 16:15 UTC, dnadales commented
> Maybe we should add `stack-local.yaml` to the `.gitignore` too :)

Nice catch. Thanks @ruhatch !

2019-02-21 15:57 UTC, dnadales commented
I'm closing this one and making a new one.

2019-02-21 15:57 UTC, closed without merging