[#119] Add JSON canonical tests from Byron release
input-output-hk/cardano-ledger-byron pull request #310
Opened 2019-02-07 13:55 UTC by Jimbo4350

https://github.com/input-output-hk/cardano-chain/issues/119
Closes #119

2019-02-07 18:23 UTC, mhuesch requested changes
Looks good! Minor question before I approve.

2019-02-07 18:23 UTC, mhuesch commented on test/Test/Cardano/Chain/Slotting/Gen.hs
> +  EpochIndex <$> Gen.word64 (Range.constant 0 maxCanonicalLovelaceVal)
What is the relation between `maxCanonicalLovelaceVal` and `EpochIndex`? Is it just being used as `maxCanonicalJsonIntegerGiga` or something (because it is ```int54Max `div` 1e9```)? If so maybe we could rename for clarity.

2019-02-07 18:28 UTC, mhuesch commented
@Jimbo4350 Also, will other JSON instances be brought over from `cardano-sl` to `cardano-chain` later, or does this represent all of them? I made up two cursory lists of types with CanonicalJson instances by grepping in the two repo's - are some of those types missing or do they represent refactoring / renaming where the old types are no longer needed?

[cardano-chain_canonical_json.txt](https://github.com/input-output-hk/cardano-chain/files/2842192/cardano-chain_canonical_json.txt)
[cardano-sl_canonical_json.txt](https://github.com/input-output-hk/cardano-chain/files/2842193/cardano-sl_canonical_json.txt)

2019-02-07 18:47 UTC, Jimbo4350 commented on test/Test/Cardano/Chain/Slotting/Gen.hs
> +  EpochIndex <$> Gen.word64 (Range.constant 0 maxCanonicalLovelaceVal)
We are actually removing this. Canonical JSON uses 54-bit integers. My understanding is @ruhatch wrote instances to avoid overflow errors (e.g https://github.com/input-output-hk/cardano-prelude/blob/master/src/Cardano/Prelude/Json/Canonical.hs#L104)

However a couple of the types' Canonical JSON instances are converting them to `Int54`s. In my debugging I restricted `genCanonicalEpochIndex` to only produce indicies within the bounds of `Int54`. We decided instead of having a `genCanonicalEpochIndex`, we would modify the types that have Canonical instances that demand an `Int54`. Is this clear?

2019-02-07 20:15 UTC, mhuesch commented on test/Test/Cardano/Chain/Slotting/Gen.hs
> +  EpochIndex <$> Gen.word64 (Range.constant 0 maxCanonicalLovelaceVal)
> We are actually removing this. Canonical JSON uses 54-bit integers. My understanding is @ruhatch wrote instances to avoid overflow errors (e.g https://github.com/input-output-hk/cardano-prelude/blob/master/src/Cardano/Prelude/Json/Canonical.hs#L104)

Ok, right. Those instances should either wrap the JSNum's into the smaller types (Word32/16, Int32) or promote them (no wrapping since the # of bits is greater than 54) into Word64, Integer, Natural.

> However a couple of the types' Canonical JSON instances are converting them to `Int54`s. In my debugging I restricted `genCanonicalEpochIndex` to only produce indicies within the bounds of `Int54`. We decided instead of having a `genCanonicalEpochIndex`, we would modify the types that have Canonical instances that demand an `Int54`. Is this clear?

I'm a little confused by the wording here - "We decided instead of having a `genCanonicalEpochIndex`" - but we have that, don't we?

2019-02-07 20:27 UTC, mhuesch commented on test/Test/Cardano/Chain/Slotting/Gen.hs
> +  EpochIndex <$> Gen.word64 (Range.constant 0 maxCanonicalLovelaceVal)
I've been able to run `stack test cardano-chain` successfully with this patch applied:
```
diff --git a/test/Test/Cardano/Chain/Slotting/Gen.hs b/test/Test/Cardano/Chain/Slotting/Gen.hs
index c2e2efc..3b538a5 100644
--- a/test/Test/Cardano/Chain/Slotting/Gen.hs
+++ b/test/Test/Cardano/Chain/Slotting/Gen.hs
@@ -46,7 +46,7 @@ import Test.Cardano.Crypto.Gen (genProtocolMagicId)
 
 genCanonicalEpochIndex :: Gen EpochIndex
 genCanonicalEpochIndex =
-  EpochIndex <$> Gen.word64 (Range.constant 0 maxCanonicalLovelaceVal)
+  EpochIndex <$> Gen.word64 (Range.constant 0 (100000000 * maxCanonicalLovelaceVal))
 
 genEpochIndex :: Gen EpochIndex
 genEpochIndex = EpochIndex <$> Gen.word64 Range.constantBounded
```
that is, multiplying the supposed max value by 10^8. Oddly, if I multiply by 10^9 I observe failures. So something odd is happening here with the Int54 max value, but I'm not sure what. It seems we have more room at the top end than your original generator was assuming, though. Unless I'm misunderstanding...

2019-02-07 20:40 UTC, Jimbo4350 commented
> @Jimbo4350 Also, will other JSON instances be brought over from `cardano-sl` to `cardano-chain` later, or does this represent all of them? I made up two cursory lists of types with CanonicalJson instances by grepping in the two repo's - are some of those types missing or do they represent refactoring / renaming where the old types are no longer needed?
> 
> [cardano-chain_canonical_json.txt](https://github.com/input-output-hk/cardano-chain/files/2842192/cardano-chain_canonical_json.txt)
> [cardano-sl_canonical_json.txt](https://github.com/input-output-hk/cardano-chain/files/2842193/cardano-sl_canonical_json.txt)

These are the canonical JSON tests in Byron:
https://github.com/input-output-hk/cardano-sl/blob/ccca8b346413f12e9fad8cab4c855e69669a2151/lib/test/Test/Pos/Genesis/CanonicalSpec.hs

Golden test for `GenesisData`
https://github.com/input-output-hk/cardano-sl/blob/577c82944042ca46a916ba86683b5db149acd49e/chain/test/Test/Pos/Chain/Genesis/Json.hs#L141

I implemented the tests above. The other tests I implemented were mainly for debugging purposes. Most of those types in your grep search are subtypes of `GenesisData` so we should be ok.

2019-02-07 20:58 UTC, mhuesch commented
@Jimbo4350 Thanks! Sorry for being hard-nosed but wanted to make sure I'm not missing something. Seems like the list of types I see in `cardano-sl` which aren't reflected verbatim in `cardano-chain` is
```
GenesisProtocolConstants
SharedSeed
Timestamp
VssCertificate
VssCertificatesMap
VssMaxTTL
VssMinTTL
ProxySKHeavy
```
I assume those just have different names in `cardano-chain` or have been revised into different types. Looks good to me then 👍

2019-02-08 17:06 UTC, mhuesch approved these changes
LGTM 🚢 :shipit: 🔥

2019-02-08 17:06 UTC, mhuesch commented
bors r+

2019-02-08 17:49 UTC, merged