[#319] Add `Lovelace` property tests
input-output-hk/cardano-ledger-byron pull request #322
Opened 2019-02-12 18:48 UTC by Jimbo4350

Closes #319

2019-02-12 20:47 UTC, mhuesch requested changes
Looks good! Minor misuse of `eachOf` which could be rewritten.

2019-02-12 20:47 UTC, mhuesch commented on test/Test/Cardano/Chain/Common/LovelaceSpec.hs
> +  (assertEitherIsLeft (addLovelace (mkKnownLovelace @1)))
I think this could be written as `property $ assertEitherIsLeft (addLovelace (mkKnownLovelace @1)) lovelaceMaxval`, no?

[`property`](https://hackage.haskell.org/package/hedgehog-0.6.1/docs/Hedgehog.html#v:property) takes a PropertyT and produces a Property. `assertEitherIsLeft` has a MonadTest instance, so should be able to get instantiated at PropertyT type.

And same goes for the other `eachOf 1 ...` properties below.

2019-02-12 20:47 UTC, mhuesch commented on test/Test/Cardano/Chain/Common/LovelaceSpec.hs
> +  -- in case expression
These could be indented over in line with `a <- ...` below.

2019-02-12 21:21 UTC, Jimbo4350 commented on test/Test/Cardano/Chain/Common/LovelaceSpec.hs
> +  (assertEitherIsLeft (addLovelace (mkKnownLovelace @1)))
Yep this can def work, I was just trying to reuse functions from `cardano-prelude`

2019-02-13 07:42 UTC, mhuesch approved these changes

2019-02-13 09:01 UTC, ruhatch approved these changes
Just a couple of small changes!

2019-02-13 09:01 UTC, ruhatch commented on test/Test/Cardano/Chain/Common/LovelaceSpec.hs
> +module Test.Cardano.Chain.Common.LovelaceSpec
Could you remove `Spec` from this? I think the module name is enough without it :)

2019-02-13 09:01 UTC, ruhatch commented on test/Test/Cardano/Chain/Common/LovelaceSpec.hs
> +lovelaceMaxval :: Lovelace
You don't need this, you can just use `maxBound`

2019-02-13 16:09 UTC, Jimbo4350 commented
bors r+

2019-02-13 16:49 UTC, merged