324: Slotting property tests
input-output-hk/cardano-ledger-byron pull request #334
Opened 2019-02-20 15:50 UTC by Jimbo4350

Brought `Slotting` tests from Byron [here](https://github.com/input-output-hk/cardano-sl/blob/e1746c944ce10690678edd3fe99a8f6d15110136/core/test/Test/Pos/Core/SlottingSpec.hs) and also implemented a few of my own.

2019-02-20 15:53 UTC, Jimbo4350 commented on src/Cardano/Chain/Block/Validation.hs
> +
Here I'm propagating a `SlotIdError` through `ChainValidationError`. @ruhatch

2019-02-20 15:55 UTC, Jimbo4350 commented on src/Cardano/Chain/Slotting/SlotId.hs
>  type FlatSlotId = Word64
Considering making this a `newtype` and not exposing the constructor. Therefore the only way to create a `FlatSlotId` would be via `flattenSlotId`. @mhuesch  @ruhatch

2019-02-20 19:48 UTC, dnadales commented on test/Test/Cardano/Chain/Slotting/Slotting.hs
> +prop_slotIdFromEnumToEnum = withTests 1000 . property $ do
Just curious: why are we running 1000 tests every time? Isn't 100 enough?

2019-02-21 15:59 UTC, mhuesch requested changes
Requesting a couple tweaks.

2019-02-21 15:59 UTC, mhuesch commented on src/Cardano/Chain/Slotting/SlotId.hs
>  type FlatSlotId = Word64
That seems reasonable to me. I like `newtype`s for added clarity at no performance cost. The only downside (I think) is that people have to use `flattenSlotId` when they want to create a static `FlatSlotId`, but that's a pretty minor inconvenience.

2019-02-21 15:59 UTC, mhuesch commented on stack.yaml
> +    commit: d71ddaacf474bfc9b96f96ce1b7c0e81a156d719
Note to self: this is the addition of the `compareValueRight` helper function [here](https://github.com/input-output-hk/cardano-prelude/commit/d71ddaacf474bfc9b96f96ce1b7c0e81a156d719).

2019-02-21 15:59 UTC, mhuesch commented on src/Cardano/Chain/Slotting/SlotId.hs
> +  $ SlotIdOverflow si sc
I find this indentation confusing. I think
```
  | pastSlots + lsi > fromIntegral (maxBound :: Word64) = Left
    $ SlotIdOverflow si sc
```
or
```
  | pastSlots + lsi > fromIntegral (maxBound :: Word64) =
    Left $ SlotIdOverflow si sc
```
would be more readable. But, I'm not super familiar with the idioms used in `cardano-chain`...

2019-02-21 15:59 UTC, mhuesch commented on src/Cardano/Chain/Slotting/SlotId.hs
> +  lsi   = case mkLocalSlotIndex es (fromIntegral slot) of
Isn't the only change here that `es` must be unwrapped, rather than just `fromIntegral`-ed?

Seems like we could do:
```
  (epoch, slot) = n `divMod` getSlotCount es
  lsi           = case mkLocalSlotIndex es (fromIntegral slot) of
```
instead.

Regardless, I suggest we use either [`div` and `mod`] or [`quot` and `rem`], since they have different truncation behaviors. It's unlikely it'd cause problems since these are Word values, but I think it's worth avoiding potential confusion. See [here](https://www.stackage.org/haddock/lts-12.17/base-4.11.1.0/Prelude.html#v:divMod) and [here](https://code.i-harness.com/en/q/59e444).

2019-02-21 15:59 UTC, mhuesch commented on test/Test/Cardano/Chain/Slotting/Slotting.hs
> +  (assertEitherIsLeft validateSlottingDataMap)
Meta-question: if some of these errors are specific and "part of the API" (in that they should stay the same across time), should we consider checking that the `Left` contains a specific error datatype? This test could pass, for example, if either a `SlottingDataTooFewIndices` or a `SlottingDataInvalidIndices` was returned. Comparing values for equality would be a hassle though.

This is more a point for future discussion...

2019-02-21 15:59 UTC, mhuesch commented on test/Test/Cardano/Chain/Slotting/Slotting.hs
> +  compareValueRight lsi succPred
👍 for `Id` tests

2019-02-21 15:59 UTC, mhuesch commented on src/Cardano/Chain/Slotting/Data.hs
> +unsafeSlottingData = SlottingData
Does the `unsafe` prefix mean this should only be used in tests? If so, could be good to add a comment/docstring

2019-02-21 15:59 UTC, mhuesch commented on test/Test/Cardano/Chain/Slotting/Gen.hs
> +genSlotCount = SlotCount <$> Gen.word64 (Range.linear 1 32767)
The hardcoded value is `2^15 - 1` which would be `maxBound :: Int16`. `maxBound :: Word16` is `65535`, though.

Perhaps we could do something like this patch?
```
diff --git a/test/Test/Cardano/Chain/Slotting/Gen.hs b/test/Test/Cardano/Chain/Slotting/Gen.hs
index 8bdb5a3..1ad9382 100644
--- a/test/Test/Cardano/Chain/Slotting/Gen.hs
+++ b/test/Test/Cardano/Chain/Slotting/Gen.hs
@@ -71,7 +71,10 @@ genLocalSlotIndex epochSlots = mkLocalSlotIndex'
 -- Restricted to upper bound of `Word16` because `mkLocalSlotIndex`
 -- creates a `LocalSlotIndex` which is limited to a `Word16`.
 genSlotCount :: Gen SlotCount
-genSlotCount = SlotCount <$> Gen.word64 (Range.linear 1 32767)
+genSlotCount = SlotCount <$> Gen.word64 (Range.linear 1 w16Max)
+ where
+  w16Max :: Word64
+  w16Max = fromIntegral (maxBound :: Word16)
 
 genSlotId :: SlotCount -> Gen SlotId
 genSlotId epochSlots =
```

2019-02-21 20:11 UTC, Jimbo4350 commented on src/Cardano/Chain/Slotting/SlotId.hs
> +  $ SlotIdOverflow si sc
Definitely, `brittany` does some weird things sometimes.

2019-02-21 21:25 UTC, mhuesch commented on src/Cardano/Chain/Slotting/SlotId.hs
> +  $ SlotIdOverflow si sc
Ah - if it's an automated indentation thing then that's cool.

2019-02-22 09:11 UTC, ruhatch commented on src/Cardano/Chain/Slotting/SlotId.hs
> +  $ SlotIdOverflow si sc
Yeah, I'm unhappy with `brittany`s indentation on guards, I might talk to the author about it

2019-02-22 09:14 UTC, ruhatch commented on test/Test/Cardano/Chain/Slotting/Gen.hs
> +genSlotCount = SlotCount <$> Gen.word64 (Range.linear 1 32767)
I don't understand this one - why do we only want to generate up to `Word16`s `maxBound`?

2019-02-22 09:38 UTC, ruhatch submitted a review, later dismissed
Looks good in general, just a few comments

2019-02-22 09:38 UTC, ruhatch commented on src/Cardano/Chain/Slotting/LocalSlotIndex.hs
> +  Left  err -> throwError err
I think you can put the body on `mkLocalSlotIndex_` into here and use `MonadError` stuff directly. The caller can interpret that as an `Either` if they choose to, because `Either` has a `MonadError` instance. So:
```
mkLocalSlotIndex
  :: MonadError LocalSlotIndexError m => SlotCount -> Word16 -> m LocalSlotIndex
mkLocalSlotIndex es idx =
  | idx < fromIntegral es = pure (UnsafeLocalSlotIndex idx)
  | otherwise = throwError $ LocalSlotIndexOverflow es (fromIntegral idx)
```

2019-02-22 09:38 UTC, ruhatch commented on src/Cardano/Chain/Slotting/SlotId.hs
> +  | pastSlots + lsi > fromIntegral (maxBound :: Word64) = Left
Can use `flattened` here

2019-02-22 09:38 UTC, ruhatch commented on test/Test/Cardano/Chain/Slotting/Gen.hs
> +genSlotCount = SlotCount <$> Gen.word64 (Range.linear 1 32767)
I think this generator should stay covering all `Word64` and if you want a restricted one you should add another one with a clear name. `genSlotCount` just sounds like it should cover all values that `SlotCount` can take.

2019-02-22 09:38 UTC, ruhatch commented on test/Test/Cardano/Chain/Slotting/Gen.hs
> +genSlotCount = SlotCount <$> Gen.word64 (Range.linear 1 32767)
Ah, I see what this is for now - I'd say add a `genEpochSlots :: Gen SlotCount`, as that's what you really want to generate right?

2019-02-22 09:38 UTC, ruhatch commented on test/Test/Cardano/Chain/Slotting/Slotting.hs
> +prop_mkSlottingData :: Property
Please document all of these `Property`s so we know what they're trying to do in English before reading the code

2019-02-22 09:38 UTC, ruhatch commented on test/Test/Cardano/Chain/Slotting/Slotting.hs
> +prop_slotIdFromEnumToEnum = withTests 1000 . property $ do
Alternatively make it dependent on the `TestScenario`, see `Test.Options`

2019-02-22 09:38 UTC, ruhatch commented on test/cardano-chain-test.cabal
> +                       Test.Cardano.Chain.Slotting.Slotting
Maybe `Test.Cardano.Chain.Slotting.Properties`?

2019-02-22 11:20 UTC, dnadales commented on src/Cardano/Chain/Slotting/SlotId.hs
> +  $ SlotIdOverflow si sc
Actually I think it isn't cool :D In most of the cases, I think we know what's the most sensible layout that will contribute to readability. I'd be in favor of disabling `brittany`, since I don't see that it is helping us.

2019-02-22 12:04 UTC, Jimbo4350 commented on src/Cardano/Chain/Slotting/SlotId.hs
> +  $ SlotIdOverflow si sc
I disagree. We've bikeshed this way too much and I'd rather fix the odd style error than have to think about code formatting again.

2019-02-22 13:06 UTC, dnadales commented on src/Cardano/Chain/Slotting/SlotId.hs
> +  $ SlotIdOverflow si sc
But we do have to think about how to format our code! In the parts we don't use `brittany` (the `specs` directory, now moved to `fm-ledger-rules`) I don't recall having a single discussion about code formatting.

Usually the author has a good reason for formatting the code the way she/he does, and when the discussion gets subjective we might just back off and accept that we're different people :)

Right now `brittany` would happily put the arguments of a function stacked up below and *to the left* of the function identifier. Also it messes with the case statements just because it blindly tries to obey the 80 characters limit:

![image](https://user-images.githubusercontent.com/175315/53244363-f7213680-36aa-11e9-9a77-fa739f25c05e.png)

I'd be happy if we could use our common sense, learn from each other, and make peace with the fact that some people won't format the code the way we'd like :)

2019-02-22 13:35 UTC, Jimbo4350 commented on test/Test/Cardano/Chain/Slotting/Slotting.hs
> +  (assertEitherIsLeft validateSlottingDataMap)
I think its a good idea that the appropriate error datatype is matched but to also reproduce and match the specific values within the datatype may be challenging.

2019-02-22 13:40 UTC, Jimbo4350 commented on src/Cardano/Chain/Slotting/Data.hs
> +unsafeSlottingData = SlottingData
The data constructor for `SlottingData` wasn't initially exposed so I created this function.

2019-02-22 14:27 UTC, Jimbo4350 commented on test/Test/Cardano/Chain/Slotting/Gen.hs
> +genSlotCount = SlotCount <$> Gen.word64 (Range.linear 1 32767)
Yeah, `LocalSlotIndex` is restricted to `Word16` and this led to overflow errors when using `genSlotCount` without restricting it to the upperbound of `Word16`. I'll make a separate generator :)

2019-02-22 16:07 UTC, mhuesch commented on src/Cardano/Chain/Slotting/Data.hs
> +unsafeSlottingData = SlottingData
Right, I understand the motivation, I was just wondering if it truly is "unsafe", in the sense that invariants must be checked by the caller (e.g. verifying that the map is consistent in some way).

If it's not "unsafe", perhaps we could rename it `makeSlottingData :: Map EpochIndex EpochSlottingData -> SlottingData`.

2019-02-22 16:20 UTC, Jimbo4350 commented on src/Cardano/Chain/Slotting/Data.hs
> +unsafeSlottingData = SlottingData
Yep there are invariants that must be checked: https://github.com/input-output-hk/cardano-chain/blob/f46c72cd72b58215d6773c4bbffc77cfd21413a8/src/Cardano/Chain/Slotting/Data.hs#L130

2019-02-22 16:22 UTC, mhuesch commented on test/Test/Cardano/Chain/Slotting/Slotting.hs
> +  (assertEitherIsLeft validateSlottingDataMap)
Yes, exactly. We'd want a way to assert that a certain constructor was used, while ignoring the values contained in the constructor.

This [StackOverflow Question](https://stackoverflow.com/questions/10112733/haskell-simple-constructor-comparison-function) is asking about what we want, and I think some of the answers would work for us. But I think this should be added as a separate work item / ticket, where we can decide how important it is and prioritize accordingly. It could take a bit of time to do cleanly for all error types.

2019-02-22 16:24 UTC, mhuesch commented on src/Cardano/Chain/Slotting/Data.hs
> +unsafeSlottingData = SlottingData
D'oh, sorry, I missed that function right above 😅

`unsafeSlottingData` is good then, and I think adding a comment to say "this doesn't check invariants, use at your own risk. Ideally this should only be used in tests" would be great.

2019-02-22 17:24 UTC, Jimbo4350 commented on test/Test/Cardano/Chain/Slotting/Slotting.hs
> +  (assertEitherIsLeft validateSlottingDataMap)
I'll create an issue :slightly_smiling_face:

2019-02-22 22:02 UTC, mhuesch approved these changes

2019-02-25 19:46 UTC, Jimbo4350 commented
bors r+

2019-02-25 20:39 UTC, Jimbo4350 commented
bors r+

2019-02-25 21:16 UTC, merged