342: Implement `Cardano.Chain.Update` property tests
input-output-hk/cardano-ledger-byron pull request #343
Opened 2019-02-28 16:39 UTC by Jimbo4350

Closes #342

2019-02-28 16:53 UTC, Jimbo4350 commented on test/Test/Cardano/Chain/Update/Gen.hs
> +  ApplicationName <$> Gen.text (Range.constant 0 12) Gen.alphaNum
`applicationNameMaxLength `: 
https://github.com/input-output-hk/cardano-chain/blob/4396cf999735800c5d197e8f809e1e5e1cf82fd6/src/Cardano/Chain/Update/ApplicationName.hs#L67

2019-02-28 17:40 UTC, mhuesch reviewed
I think that exporting `applicationNameMaxLength` and using it instead of a hardcoded `12` would be good.

2019-02-28 17:40 UTC, mhuesch commented on test/Test/Cardano/Chain/Update/Gen.hs
> +  ApplicationName <$> Gen.text (Range.constant 0 12) Gen.alphaNum
Is it possible to export the variable from `Cardano.Chain.Update.ApplicationName`, and thus DRY this bit up? Otherwise there could be breakage if the max length changes.

2019-02-28 17:40 UTC, mhuesch commented on test/Test/Cardano/Chain/Update/Properties.hs
> +    (\name -> T.length (getApplicationName name) >= 12)
This could also use the `applicationNameMaxLength` var.

2019-02-28 17:40 UTC, mhuesch commented on test/Test/Cardano/Chain/Update/Properties.hs
> +    (\name -> T.length (getApplicationName name) >= 12)
This could also use the `applicationNameMaxLength` var.

2019-02-28 17:40 UTC, mhuesch commented on test/Test/Cardano/Chain/Update/Properties.hs
> +    (Gen.string (Range.linear 1 12) Gen.unicodeAll)
This could also use the `applicationNameMaxLength` var.

2019-02-28 17:40 UTC, mhuesch commented on test/Test/Cardano/Chain/Update/Properties.hs
> +    (Gen.string (Range.linear 1 12) Gen.unicodeAll)
This could also use the `applicationNameMaxLength` var.

2019-02-28 17:40 UTC, mhuesch commented on test/Test/Cardano/Chain/Update/Properties.hs
> +    (Gen.string (Range.linear 1 12) Gen.unicodeAll)
This could also use the `applicationNameMaxLength` var.

2019-02-28 17:43 UTC, Jimbo4350 commented on test/Test/Cardano/Chain/Update/Gen.hs
> +  ApplicationName <$> Gen.text (Range.constant 0 12) Gen.alphaNum
Definitely, I'll make the change.

2019-03-01 16:02 UTC, mhuesch requested changes
I noticed that `SystemTag` has the same issue - would be good to fix both so they are more DRY.

2019-03-01 16:02 UTC, mhuesch commented on test/Test/Cardano/Chain/Update/Properties.hs
> +    $ Gen.filter (\sysTag -> T.length (getSystemTag sysTag) >= 10) genSystemTag
I missed this last time, but `genSystemTag` has the same non-DRY issue. Using `systemTagMaxLength` from `Cardano.Chain.Update.SystemTag` would clean it up.

2019-03-01 16:02 UTC, mhuesch commented on test/Test/Cardano/Chain/Update/Properties.hs
> +-- Make sure `checkApplicationName` fails on names that are too long (> 12).
We could also drop the `(> 12)` and `(> 10)` comments, since they could go stale and nobody would notice. Checking the max is self evident from the code.

2019-03-01 16:39 UTC, mhuesch commented
`genSystemTag` still has a hardcoded `10`

2019-03-01 17:10 UTC, mhuesch approved these changes

2019-03-01 17:10 UTC, mhuesch commented
LGTM! :shipit:

2019-03-01 17:10 UTC, Jimbo4350 commented
bors r+

2019-03-01 17:13 UTC, Jimbo4350 commented
bors r-

2019-03-01 18:45 UTC, Jimbo4350 commented
bors r+

2019-03-01 19:24 UTC, merged