Implement the update endorsement rules
input-output-hk/cardano-ledger-byron pull request #353
Opened 2019-03-13 13:22 UTC by dnadales

2019-03-13 21:13 UTC, mhuesch approved these changes
Looks good! I noted some optional tweaks and questions.

2019-03-13 21:13 UTC, mhuesch commented on src/Cardano/Chain/Common/BlockCount.hs
> +    { unBlockCount :: Word64
Just curious - is `un<..>` preferred over `get<..>`? We seem to use both for newtype fields in this repo. I have no real preference, just wondering.

2019-03-13 21:13 UTC, mhuesch commented on src/Cardano/Chain/Update/Validation/Endorsement.hs
> +  -- genesis keys that need to endorse a new protocol version to considered for
```suggestion
  -- genesis keys that need to endorse a new protocol version for it to be considered for
```

or perhaps

```suggestion
  -- genesis keys which must endorse a new protocol version for it to be considered for
```

?

2019-03-13 21:13 UTC, mhuesch commented on src/Cardano/Chain/Update/Validation/Endorsement.hs
> +  t = lovelacePortionToDouble ppUpdateProposalThd * fromIntegral n
I was pretty confused by this part, but I think I figured it out. I want to check my understanding, though.

The spec says
```
canAdopt pps bvs bv = upAdptThd |→ t ∈ pps ∧ t ≤ |{bv} <| bvs|

-- (`<|` being domain restriction)
```

which seems to indicate `t` will be an integer number Genesis Keys. We must have that number, or more, of endorsements for a specific BlockVersion, for it to be adopt-able.

***

In this code, we seem to be making an assumption that stake is evenly distributed among Genesis Keys (I think this is true, but still an assumption). Thus we can determine the threshold number `t` of Genesis Keys needed to adopt an update. We filter the set to find endorsements for a given BlockVersion, and compare that to `t`.

***

Since we're using LovelacePortion, I was expecting we would compute that actual stake of the Genesis Keys and compare that against the threshold. However that would be more complex, so this seems tidier, given that the equal-stake assumption holds.

***

```suggestion
  -- Here we assume that stake is evenly distributed among the Genesis Keys.
  -- Thus, the LovelacePortion can be multiplied by the number of keys to yield
  -- the endorsement threshold.
  t = lovelacePortionToDouble ppUpdateProposalThd * fromIntegral n
```

A comment like ☝️might be helpful for future readers.

2019-03-14 09:20 UTC, dnadales commented on src/Cardano/Chain/Common/BlockCount.hs
> +    { unBlockCount :: Word64
I cannot recall why we preferred `un<..>` over `get<..>`, but considering that we have to adapt the Aeson instances, maybe I'd just revert this. @ruhatch: any thoughts?

2019-03-14 09:45 UTC, dnadales commented on src/Cardano/Chain/Update/Validation/Endorsement.hs
> +  t = lovelacePortionToDouble ppUpdateProposalThd * fromIntegral n
Now that I think about it, I'm not sure that we even need to assume even distribution of the stake.

If I understand this correctly, the problem is that we don't have a `upAdptThd` protocol parameter, so we need to use one of the existing parameters. 

I think the assumption here is that `lovelacePortionToDouble ppUpdateProposalThd` will be a number around `0.5`, so if we have `7` genesis keys, we'd need more than `t = 3.5` endorsements, which would be the same as having an `upAdptThd` parameter of `4`. 

Now the problem seems to be that `ppUpdateProposalThd` (called `updateProposalThd` in `cardano-sl` if I'm not mistaken) is set to `100000000000000`, so `lovelacePortionToDouble ppUpdateProposalThd` will be `0.1`!

From `cardano-sl/lib/mainnet-genesis.json`:

```json
    "blockVersionData": {
        "heavyDelThd": "300000000000",
        "maxBlockSize": "2000000",
        "maxHeaderSize": "2000000",
        "maxProposalSize": "700",
        "maxTxSize": "4096",
        "mpcThd": "20000000000000",
        "scriptVersion": 0,
        "slotDuration": "20000",
        "softforkRule": {
            "initThd": "900000000000000",
            "minThd": "600000000000000",
            "thdDecrement": "50000000000000"
        },
        "txFeePolicy": {
            "multiplier": "43946000000",
            "summand": "155381000000000"
        },
        "unlockStakeEpoch": "18446744073709551615",
        "updateImplicit": "10000",
        "updateProposalThd": "100000000000000",
        "updateVoteThd": "1000000000000"
    },
```

So it seems we might need to change the `canAdopt` function.

I'm tempted to use `softforkRule.minThd` since ` (600000000000000 / 1e15) * 7 = 4.2`,

2019-03-14 09:56 UTC, nc6 requested changes
Some small changes requested, but otherwise looks good.

2019-03-14 09:56 UTC, nc6 commented on src/Cardano/Chain/Common/BlockCount/JSON.hs
> +unToGet :: [Char] -> [Char]
This is a very weird function unless the context behind it is explained. So can we have that context in some comments for it, please?

2019-03-14 09:56 UTC, nc6 commented on src/Cardano/Chain/Update/Validation/Endorsement.hs
> +  ( registerEndorsement
This module is going to be rather tricky to use, since the only exported function requires values of type `Environment` and `State` but offers no way to create them :-)

2019-03-14 09:56 UTC, nc6 commented on src/Cardano/Chain/Update/Validation/Endorsement.hs
> +  { fpvSlot               :: FlatSlotId
[minor] `cpv` rather than `fpv` here? I'm guessing this used to be called `FutureProtocolVersion`?

2019-03-14 09:56 UTC, nc6 commented on src/Cardano/Chain/Update/Validation/Endorsement.hs
> +  { fpvSlot               :: FlatSlotId
Can we document what slot this refers to? Things like `fpvProtocolParameters` are self-explanatory, but slots are inevitably not... is this the slot it was submitted on, the one it will come into force on, or the one it expires on?

2019-03-14 09:56 UTC, nc6 commented on src/Cardano/Chain/Update/Validation/Endorsement.hs
> +            { futureProtocolVersions = fpvs'
Any reason we're using `fpvs` here rather than `fads`, as used in the latex spec?

2019-03-14 09:56 UTC, nc6 commented on src/Cardano/Chain/Update/Validation/Endorsement.hs
> +    _2 x = 2 * unBlockCount x
I find this a rather confusing notation (I would automatically assume `_2` to be the projection lens from a tuple), though I guess it's close enough to the site to be okay. But why not just inline this?

2019-03-14 10:39 UTC, dnadales commented on src/Cardano/Chain/Common/BlockCount/JSON.hs
> +unToGet :: [Char] -> [Char]
I reverted the change. I think it isn't worth the extra complexity.

2019-03-14 10:40 UTC, dnadales commented on src/Cardano/Chain/Update/Validation/Endorsement.hs
> +  ( registerEndorsement
Yeah, indeed :) As I hook this module to others I'll start adding the required exports to that list :)

2019-03-14 10:40 UTC, dnadales commented on src/Cardano/Chain/Update/Validation/Endorsement.hs
> +  { fpvSlot               :: FlatSlotId
Good catch! Bad programmer, bad programmer :newspaper_roll:

2019-03-14 10:41 UTC, dnadales commented on src/Cardano/Chain/Update/Validation/Endorsement.hs
> +  { fpvSlot               :: FlatSlotId
Good point! Thanks for bringing this to my attention. I'll add some documentation now.

2019-03-14 10:48 UTC, dnadales commented on src/Cardano/Chain/Update/Validation/Endorsement.hs
> +            { futureProtocolVersions = fpvs'
I guess since we called that field of the state "future protocol versions ", `fpvs` is a suitable acronym, although it differs from the spec.

2019-03-14 10:49 UTC, dnadales commented on src/Cardano/Chain/Update/Validation/Endorsement.hs
> +    _2 x = 2 * unBlockCount x
Indeed. I just changed that.

2019-03-14 11:11 UTC, ruhatch approved these changes
LGTM! Thanks for finishing this and tidying up!

2019-03-14 11:13 UTC, nc6 approved these changes

2019-03-14 11:13 UTC, nc6 commented on src/Cardano/Chain/Update/Validation/Endorsement.hs
> +    -- following epochs.
Great, thanks!

2019-03-14 12:49 UTC, dnadales commented
bors r+

2019-03-14 16:15 UTC, mhuesch reviewed
Another Q 🙂

2019-03-14 16:15 UTC, mhuesch commented on src/Cardano/Chain/Update/Validation/Endorsement.hs
> +  -- will evaluate to @0.6@, so if we have 7 genesis keys, @upAdptThd = 4@.
Thanks! I find this implementation more clear.

I now am confused by a different point - rounding of the `stakeRatio * fromIntegral ngk`. Shouldn't that be `ceiling`? If we insist that `0.6 * 7 = 4.2` or more nodes agree, shouldn't we round up to 5?

Alternately we could stay with `floor` but say `upAdptThd < numberOfEndorsements` as the final conditional (strict GT).

2019-03-14 16:38 UTC, mhuesch commented on src/Cardano/Chain/Update/Validation/Endorsement.hs
> +  t = lovelacePortionToDouble ppUpdateProposalThd * fromIntegral n
> Now that I think about it, I'm not sure that we even need to assume even distribution of the stake.
> 
> If I understand this correctly, the problem is that we don't have a upAdptThd protocol parameter, so we need to use one of the existing parameters.

Isn't this a separate issue, though? If we're translating from "percentage of total stake which must endorse this proposal" to "percentage of genesis keys, which all together control the total stake, which must endorse this proposal", it seems to me that we need to know how much stake they control (or assume it's evenly split).

I believe that `softforkRule.minThd` is appropriate to use here. In `cardano-sl`, update adoption was triggered when the percentage of stake endorsing the new BlockVersion exceeded the softforkRule threshold (although it used the moving target, which we're not).

2019-03-14 20:03 UTC, dnadales commented on src/Cardano/Chain/Update/Validation/Endorsement.hs
> +  -- will evaluate to @0.6@, so if we have 7 genesis keys, @upAdptThd = 4@.
I don't know what the right value should be: `4` or `5`, but I guess we can tweak this as needed.

2019-03-14 20:06 UTC, dnadales commented on src/Cardano/Chain/Update/Validation/Endorsement.hs
> +  t = lovelacePortionToDouble ppUpdateProposalThd * fromIntegral n
> Isn't this a separate issue, though? If we're translating from "percentage of total stake which must endorse this proposal" to "percentage of genesis keys, which all together control the total stake, which must endorse this proposal", it seems to me that we need to know how much stake they control (or assume it's evenly split).

Well the thing is that in this case we don't care about the stake they control, all we care is that they are genesis keys.

However if this brings too much confusion we might need to introduce a protocol parameter with a default value.

> I believe that softforkRule.minThd is appropriate to use here. In cardano-sl, update adoption was triggered when the percentage of stake endorsing the new BlockVersion exceeded the softforkRule threshold (although it used the moving target, which we're not).

Great! Thanks for confirming this :)

2019-03-14 20:07 UTC, dnadales commented
bors r+

2019-03-14 21:18 UTC, merged