Implement UPIREG and UPIVOTE rules
input-output-hk/cardano-ledger-byron pull request #355
Opened 2019-03-14 16:00 UTC by dnadales

2019-03-14 16:08 UTC, ruhatch requested changes
The general structure looks good, but I don't want to use lenses in the implementation at all! Just need to recast in the style of the other rules so far.

2019-03-14 16:08 UTC, ruhatch commented on src/Cardano/Chain/Update/Validation/Interface.hs
> +makeLenses ''Environment
Sorry, I don't think we're going to use lenses in the implementation anywhere!

2019-03-14 16:08 UTC, ruhatch commented on src/Cardano/Chain/Update/Validation/Interface.hs
> +    , _registeredProtocolUpdateProposals :: !(Map UpId (ProtocolVersion, ProtocolParameters))
There's a `RegisteredProtocolUpdateProposals` (or something) type synonym in `Cardano.Chain.Update.Validation.Registration` that you could use here

2019-03-14 16:08 UTC, ruhatch commented on src/Cardano/Chain/Update/Validation/Interface.hs
> +  = Registration Registration.Error
Nice

2019-03-14 16:08 UTC, ruhatch commented on src/Cardano/Chain/Update/Validation/Interface.hs
> +    pm = env ^. protocolMagic
To stay in line with the style of all the other validation rules, please unpack the environment and state in a where clause using `NamedFieldPuns`

2019-03-14 18:08 UTC, mhuesch reviewed
Looks good. I added a few comments. Since Ru requested de-lens-ing, I'll wait to approve.

2019-03-14 18:08 UTC, mhuesch commented on src/Cardano/Chain/Update/Validation/Interface.hs
> +    , _registeredProtocolUpdateProposals :: !(Map UpId (ProtocolVersion, ProtocolParameters))
👍  [`ProtocolUpdateProposals`](https://github.com/input-output-hk/cardano-chain/blob/8194af3534721859f4fc4b5246f6820bca2bd299/src/Cardano/Chain/Update/Validation/Registration.hs#L37)

2019-03-14 18:08 UTC, mhuesch commented on src/Cardano/Chain/Update/Validation/Interface.hs
> +    , _registeredSoftwareUpdateProposals :: !(Map UpId SoftwareVersion)
There's also a synonym for this: [`SoftwareUpdateProposals`](https://github.com/input-output-hk/cardano-chain/blob/8194af3534721859f4fc4b5246f6820bca2bd299/src/Cardano/Chain/Update/Validation/Registration.hs#L38)

2019-03-14 18:08 UTC, mhuesch commented on src/Cardano/Chain/Update/Validation/Interface.hs
> +      `wrapError` Registration
I like how this reads 🙂

2019-03-14 18:08 UTC, mhuesch commented on src/Cardano/Chain/Update/Validation/Interface.hs
> +       -- TODO: consider using the `Relation` instances from `fm-ledger-rules` (see `Ledger.Core`)
Seems like a reasonable idea to me - we already depend on `cs-ledger`.

2019-03-14 18:28 UTC, mhuesch reviewed
I missed a few spots in my last review...

2019-03-14 18:28 UTC, mhuesch commented on src/Cardano/Chain/Update/Validation/Interface.hs
> +       & registeredSoftwareUpdateProposals %~ (`M.withoutKeys` S.fromAscList (M.keys cps))
There is also [`keysSet`](https://www.stackage.org/haddock/lts-12.17/containers-0.5.11.0/Data-Map-Lazy.html#v:keysSet)

2019-03-14 18:28 UTC, mhuesch commented on src/Cardano/Chain/Update/Validation/Interface.hs
> +--
In keeping with the other rules, we could write

```suggestion
-- This corresponds to the @UPIVOTE@ rules in the spec.
--
```

2019-03-14 18:28 UTC, mhuesch commented on src/Cardano/Chain/Update/Validation/Interface.hs
> +      rups = S.fromAscList $! M.keys (st ^. proposalRegistrationSlot)
There is also [`keysSet`](https://www.stackage.org/haddock/lts-12.17/containers-0.5.11.0/Data-Map-Lazy.html#v:keysSet)

2019-03-14 20:09 UTC, dnadales commented
@ruhatch if we don't want to use lenses at all maybe we'd like to make this explicit in the README or CONTRIBUTING documents. 

I also noticed that we do depend on `lens` in `cardano-chain` (I didn't add this dependency), do we want to make an issue to remove this?

2019-03-14 20:11 UTC, dnadales commented on src/Cardano/Chain/Update/Validation/Interface.hs
> +    , _registeredSoftwareUpdateProposals :: !(Map UpId SoftwareVersion)
I don't like these synonyms: they introduce additional notation that the reader has to lookup. If we use the right-hand side of the type alias we are not adding much more characters and we remove one level of indirection.

@mhuesch, @ruhatch: any thoughts?

2019-03-14 20:13 UTC, dnadales commented on src/Cardano/Chain/Update/Validation/Interface.hs
> +       & registeredSoftwareUpdateProposals %~ (`M.withoutKeys` S.fromAscList (M.keys cps))
Thanks for this tip! I should have imagined that there must be a function already defined for this common pattern :man_facepalming:

2019-03-14 20:20 UTC, dnadales commented on src/Cardano/Chain/Update/Validation/Interface.hs
> +      rups = S.fromAscList $! M.keys (st ^. proposalRegistrationSlot)
I owe you a :beer:

2019-03-14 20:23 UTC, dnadales commented on src/Cardano/Chain/Update/Validation/Interface.hs
> +    , _registeredProtocolUpdateProposals :: !(Map UpId (ProtocolVersion, ProtocolParameters))
Oh, I commented on this below. Please let me know what do you think.

2019-03-14 20:44 UTC, dnadales commented on src/Cardano/Chain/Update/Validation/Interface.hs
> +      `wrapError` Registration
Now it is a bit better without the parenthesis :D

2019-03-14 20:46 UTC, dnadales commented on src/Cardano/Chain/Update/Validation/Interface.hs
> +    pm = protocolMagic
@ruhatch @mhuesch let me know if you're ok with these double bindings, otherwise I can split the call to `registerProposal` over several lines (or we can ask for 4K monitors :D )

2019-03-15 04:59 UTC, mhuesch commented on src/Cardano/Chain/Update/Validation/Interface.hs
> +    , _registeredSoftwareUpdateProposals :: !(Map UpId SoftwareVersion)
That's fair - the full types are fairly simple and terse, and they're only used once (as opposed to in `Cardano.Chain.Update.Validation.Registration` where they're repeated a few times).

Having the type inlined also makes it easier to compare directly with the types in the ledger-spec, which is what I did while reviewing.

2019-03-15 07:32 UTC, dnadales commented on src/Cardano/Chain/Update/Validation/Interface.hs
> +    , _registeredSoftwareUpdateProposals :: !(Map UpId SoftwareVersion)
> Having the type inlined also makes it easier to compare directly with the types in the ledger-spec, which is what I did while reviewing.

Yeah, that's also a good point. Consistency is important. So we either drop the type synonyms in `Cardano.Chain.Update.Validation.Registration` or I add them in `Cardano.Chain.Update.Validation.Interface`. I'd prefer the latter, but I can also do the former :) @ruhatch, what do you think?

2019-03-15 09:43 UTC, ruhatch requested changes

2019-03-15 09:43 UTC, ruhatch commented on src/Cardano/Chain/Update/Validation/Interface.hs
> +    pm = protocolMagic
If you want to rename them, just do:
```
Environment { protocolMagic = pm, currentSlot, delegationMap = dms }
```

Also, I'd still prefer the unpacking to be done in the `where` clause, as that allows us to read the meat of the definition and look up names as needed in some sort of index

2019-03-15 09:43 UTC, ruhatch commented on src/Cardano/Chain/Update/Validation/Interface.hs
> +    cps = confirmedProposals
Again, renaming using records, and put into `where` clause

2019-03-15 09:43 UTC, ruhatch commented on src/Cardano/Chain/Update/Validation/Interface.hs
> +       -- TODO: consider using the `Relation` instances from `fm-ledger-rules` (see `Ledger.Core`)
How would you use `Relation` instances here?

2019-03-15 09:43 UTC, ruhatch commented on src/Cardano/Chain/Update/Validation/Interface.hs
> +      -- ^ Previously seen epoch
This is really pedantic, but could you move these back two?  Also if you have stylish-haskell, could you run it to line up the type definitions here?

2019-03-15 09:43 UTC, ruhatch commented on src/Cardano/Chain/Update/Validation/Interface.hs
> +data Environment
I would prefer keeping the `= Environment` on the same line as `data Environment`, to keep in line with the rest of the code. You're right, I need to publish some style documents as I clearly have some styles!

2019-03-15 09:43 UTC, ruhatch commented on src/Cardano/Chain/Update/Validation/Interface.hs
> +import Cardano.Prelude
Please don't use explicit imports in `Cardano.Prelude` - use `hiding` if something clashes

2019-03-15 09:57 UTC, dnadales commented on src/Cardano/Chain/Update/Validation/Interface.hs
> +data Environment
For the record, what I don't like of the 

```haskell
data MyData = MyData 
  { blah ...
```

style is that the fields end to the left of the constructor. 

I'll change this as suggested, but if we write some style document it'd be nice to ask others for their input, in particular @erikd, @edsko, and the more experienced folks around us.

2019-03-15 10:00 UTC, dnadales commented on src/Cardano/Chain/Update/Validation/Interface.hs
> +import Cardano.Prelude
I'll remove this, but again for the records, the problem with the implicit imports in `Cardano.Prelude` is that there are a bunch of non-standard functions what we do not know where do they come from (think of `wrapError` for instance). Tracking these down is quite hard (mostly because `Cardano.Prelude` will re-export a lot of things implicitly).

It is a pain to explicitly import symbols from `Cardano.Prelude`, but I think we're saving pain to our readers.

2019-03-15 10:02 UTC, dnadales commented on src/Cardano/Chain/Update/Validation/Interface.hs
> +      -- ^ Previously seen epoch
Sure.

2019-03-15 10:54 UTC, dnadales commented on src/Cardano/Chain/Update/Validation/Interface.hs
> +       , registeredSoftwareUpdateProposals = raus
Ups I missed this one. I deleted this space and pushed the changes.

2019-03-15 11:12 UTC, ruhatch approved these changes
LGTM!

2019-03-15 11:20 UTC, ruhatch commented on src/Cardano/Chain/Update/Validation/Interface.hs
> +import Cardano.Prelude
Hmm, I think as long as everything else is using `qualified` or explicit imports, then it's relatively clear that it can only come from `Cardano.Prelude`

2019-03-15 11:20 UTC, ruhatch commented on src/Cardano/Chain/Update/Validation/Interface.hs
> +import Cardano.Prelude
But I do understand and like with most things, I'm back and forth!

2019-03-15 11:44 UTC, dnadales commented on src/Cardano/Chain/Update/Validation/Interface.hs
> +import Cardano.Prelude
> I think as long as everything else is using qualified or explicit imports, then it's relatively clear that it can only come from Cardano.Prelude

Yeah, that's a good point :)

2019-03-15 13:58 UTC, dnadales commented
bors r+

2019-03-15 15:15 UTC, dnadales commented
bors retry

2019-03-18 11:26 UTC, dnadales commented
bors r+

2019-03-18 12:08 UTC, merged