[285] Implement bulk chain validation with logging
input-output-hk/cardano-ledger-byron pull request #358
Opened 2019-03-14 19:18 UTC by Jimbo4350

Closes #285

2019-03-15 10:08 UTC, ruhatch requested changes
Structure looks good, just a few formatting/style suggestions. Are you going to change the config stuff in this PR or do another one for that?

2019-03-15 10:08 UTC, ruhatch commented on app/Main.hs
> +            logNotice logTrace' "No results yet!"
Could just use `do` notation here

2019-03-15 10:08 UTC, ruhatch commented on app/Main.hs
> +      featureStart bf
I think you don't need to do this part - the `runCardanoApplicationWithFeatures` is supposed to start all the features for you!

2019-03-15 10:08 UTC, ruhatch commented on app/Main.hs
> +    chainValidationApp
Maybe move this to the top level (i.e. out of the `main` function) to keep the definitions smaller

2019-03-15 10:08 UTC, ruhatch commented on cardano-chain.cabal
> +                       Cardano.Shell.Features.Blockchain
Aha, could you actually move this to the application, I don't think it should be in the `cardano-chain` library

2019-03-15 10:08 UTC, ruhatch commented on cardano-chain.cabal
> +                     , cardano-mainnet-mirror
Then you can move this dep to the application too, I really don't want this in the library dependencies!

2019-03-15 10:08 UTC, ruhatch commented on cardano-chain.cabal
> +      base >=4.7 && <5
Can you align these like the others in this file?

2019-03-15 10:08 UTC, ruhatch commented on src/Cardano/Shell/Features/Blockchain.hs
> +-- `BlockchainLayer` enables us to get the value from an MVar
You can use `-- | ...` to make this nice for Haddock

2019-03-15 10:08 UTC, ruhatch commented on src/Cardano/Shell/Features/Blockchain.hs
> +  -- Create MVar that will hold the result of the bulk chain validation.
Could use a bit more white space here (i.e. newlines above the comments on the next couple of lines)

2019-03-15 10:16 UTC, ksaric reviewed
I'll add my own comments here, but they are optional, of course, since my jurisdiction ends when you cross the `cardano-shell` county.

2019-03-15 10:16 UTC, ksaric commented on src/Cardano/Chain/Epoch/Validation.hs
> +  -> IO (Either EpochError ChainValidationState)
I don't want to go into details before other folks give a review, but wouldn't it be simpler to just use `MonadThrow/MonadCatch m` here?

2019-03-15 10:16 UTC, ksaric commented on app/Main.hs
> +              >> threadDelay 10000000
10 seconds, right? Hard to guess when they are all crammed in like that.

2019-03-15 10:16 UTC, ksaric commented on src/Cardano/Shell/Features/Blockchain.hs
> +      => m (Maybe (Either EpochError ChainValidationState))
Again, seems like a simple `MonadCatch` would do here.

2019-03-15 10:16 UTC, ksaric commented on src/Cardano/Shell/Features/Blockchain.hs
> +    Development -> take 10 <$> liftIO mainnetEpochFiles
Take the first 10 mainnet epoch files?

2019-03-15 10:16 UTC, ksaric commented on src/Cardano/Chain/Epoch/Validation.hs
> +  (\c b ->
Write down a function for readability?

2019-03-15 10:16 UTC, ksaric commented on src/Cardano/Chain/Epoch/Validation.hs
> +  -> ExceptT EpochError ResIO ChainValidationState
:scream:

2019-03-15 10:16 UTC, ksaric commented on src/Cardano/Chain/Epoch/Validation.hs
> +  where stream = parseEpochFilesWithBoundary fps
Repetition?

2019-03-15 10:21 UTC, ruhatch commented on src/Cardano/Chain/Epoch/Validation.hs
> +  -> IO (Either EpochError ChainValidationState)
Yeah, although we prefer `MonadError`, so `(MonadIO m, MonadError EpochError m) => ...`

2019-03-15 10:22 UTC, ruhatch commented on app/Main.hs
> +              >> threadDelay 10000000
Yeah, I'd suggest `NumDecimals`, so you can write `1e7`

2019-03-15 10:25 UTC, ruhatch commented on src/Cardano/Shell/Features/Blockchain.hs
> +      => m (Maybe (Either EpochError ChainValidationState))
I'm not sure about this one actually, I'd probably leave it as it is

2019-03-15 14:13 UTC, Jimbo4350 commented on cardano-chain.cabal
> +                       Cardano.Shell.Features.Blockchain
Will do!

2019-03-15 19:53 UTC, Jimbo4350 commented on src/Cardano/Shell/Features/Blockchain.hs
> +      => m (Maybe (Either EpochError ChainValidationState))
@ksaric what's your rationale here?

2019-03-15 20:37 UTC, mhuesch commented on src/Cardano/Chain/Epoch/Validation.hs
> +  -> IO (Either EpochError ChainValidationState)
Jordan asked me for input on this -

I don't see that `MonadError` gets us anything here. We have a function which _could_ be generalized, but is only used [here](https://github.com/input-output-hk/cardano-chain/pull/358/files#diff-fed5b16ab90a046803ddac97cd51193dR59) at its specialized type, in order to return an `Either EpochError ChainValidationState` which goes into an MVar, which is specialized to that type.

So, generalizing in order to specialize doesn't make sense to me.

I agree that `MonadError` is useful in many situations, because of ease of composition, etc. But I don't see that here.

2019-03-15 21:02 UTC, mhuesch commented on src/Cardano/Shell/Features/Blockchain.hs
> +      => m (Maybe (Either EpochError ChainValidationState))
If we keep this as a concrete `Either EpochError ChainValidationState`, then I don't see the point in generalizing [above](https://github.com/input-output-hk/cardano-chain/pull/358#discussion_r265922486), since we would just have to re-specialize [here](https://github.com/input-output-hk/cardano-chain/blob/426db475a1f3dae561af9b81075c8cc68bb1b38f/app/Features/Blockchain.hs#L59).

I don't really see the point in generalizing here, since there's only one usage site for the `chainValidationStatus` accessor.

2019-03-15 23:05 UTC, ksaric commented on src/Cardano/Shell/Features/Blockchain.hs
> +      => m (Maybe (Either EpochError ChainValidationState))
This is up to you guys to decide, just wrote down my opinion.
My rationale here, and in general, when it's concerning `Either` is that it seems to me to be good for smaller chunks of code, that don't propagate over several functions.
My experience is that `Either` doesn't compose nicely into the transformer stack and when you think about it, all the functions where you drag `Either` are functions which you "infect" with that "effect", which means you "need" transformer stack composition there anyway.

2019-03-18 13:23 UTC, ruhatch approved these changes
Looks good, just a couple of things to address!

2019-03-18 13:23 UTC, ruhatch commented on cardano-chain.cabal
> +                     , cardano-shell
You should be able to remove these now, right?

2019-03-18 13:23 UTC, ruhatch commented on cardano-chain.cabal
> +  ghc-options:         -Wall
See the other sections of this cabal file for the standard `ghc-options` we use

2019-03-18 13:23 UTC, ruhatch commented on test/Test/Cardano/Chain/Block/Validation.hs
> +  , blockSlot
Can you revert the changes to this file, they don't seem particularly relevant!

2019-03-18 14:13 UTC, Jimbo4350 commented on src/Cardano/Shell/Features/Blockchain.hs
> +      => m (Maybe (Either EpochError ChainValidationState))
Decided to keep things explicit for now, the `Either` isn't propagating very far at the moment and if we need to generalize in the future we can.

2019-03-18 14:17 UTC, Jimbo4350 commented on test/Test/Cardano/Chain/Block/Validation.hs
> +  , blockSlot
Needed here: https://github.com/input-output-hk/cardano-chain/pull/358/files#diff-8fb0ac17f82ff048bc35a27ffe8a766aR78

2019-03-18 20:19 UTC, ruhatch commented on test/Test/Cardano/Chain/Block/Validation.hs
> +  , blockSlot
From what I can see this just moves an import around and removes some whitespace? Can you see something different?

2019-03-18 21:03 UTC, erikd commented on src/Cardano/Chain/Epoch/Validation.hs
> +  -> IO (Either EpochError ChainValidationState)
i personally consider `MonadThrow/MonadCatch` much more painful than simply dealing with the  `Either`.

In my experience, the only people who prefer `MonadError/MonadThrow/MonadCatch` are the people who don't know how to use `EitherT/ExceptT` and/or do not have access to a suitable library of useful combinators for `EitherT/ExceptT`.

2019-03-18 21:11 UTC, erikd commented on src/Cardano/Shell/Features/Blockchain.hs
> +      => m (Maybe (Either EpochError ChainValidationState))
Sorry, I *really* have to disagree here, `Either` composes far better than any `Monad*` typeclass constraint, as long as you are aware of and use the right techniques.

The problem is that the vast majority of the publicly available example code uses the `Monad*` stuff and there is almost no code that uses what I consider a better alternative.

@ksaric if you ever get into a situation where you consider `Either` a problem, please let me know and I will help you sort it out.

2019-03-18 21:12 UTC, erikd commented on src/Cardano/Chain/Epoch/Validation.hs
> +  -> ExceptT EpochError ResIO ChainValidationState
What is the problem here????

2019-03-18 21:31 UTC, ksaric commented on src/Cardano/Chain/Epoch/Validation.hs
> +  -> ExceptT EpochError ResIO ChainValidationState
I guess it comes down to this - it is my impression that using `mtl` is the "standard" and recommended way of using transformer stacks. Getting out of the whole "uh, I forgot to add another `lift` to `lift . lift . lift $`. 
So you prefer not to use `mtl` and like using this style, I presume?

2019-03-19 12:57 UTC, Jimbo4350 commented on test/Test/Cardano/Chain/Block/Validation.hs
> +  , blockSlot
:man_facepalming: yep, overlooked this!

2019-03-22 02:06 UTC, erikd commented on src/Cardano/Chain/Epoch/Validation.hs
> +  -> ExceptT EpochError ResIO ChainValidationState
I think we are talking about completely different things.

I am specifically talking about a preference for using `ExceptT` (with the right combinators) in preference to `MonadCatch/MonadThrow`. Using `ExceptT` makes errors far more explicit.

2019-04-05 14:59 UTC, ruhatch approved these changes
Looks good! I'd suggest removing the whole `MVar` thing for the UTxO size and just use the logging layer internally, but maybe leave that for another PR!

2019-04-05 14:59 UTC, ruhatch commented on app/Features/Blockchain.hs
> +  , currentUTxOSize
I think it might be better to do the logging for this one internal to the `BlockchainLayer`. This would also show what's it's like to have the `LoggingLayer` as a dependency of the `BlockchainFeature`. I think there's an example in `cardano-shell` that shows what it would look like to have one feature take the other as a dependency. So then you would just output `UTxO` size information after each block from inside the layer.

2019-04-05 14:59 UTC, ruhatch commented on src/Cardano/Chain/Block/Validation.hs
> +              _ <- liftIO $ takeMVar sizeMVar
This is slightly odd, I don't think you should be `take`ing from this `MVar`, because it can only be consumed by one thread. In this case the other thread might read it before you and then you'd block here forever! If you want to wait for them to read it out then `putMVar` does exactly that, it blocks until the `MVar` is empty.

2019-04-05 17:49 UTC, Jimbo4350 commented on app/Features/Blockchain.hs
> +  , currentUTxOSize
Yep that sounds reasonable. I can do that in a follow up PR.

2019-04-05 18:36 UTC, Jimbo4350 commented on src/Cardano/Chain/Block/Validation.hs
> +              _ <- liftIO $ takeMVar sizeMVar
This is read with `tryReadMVar` in the blockchain layer so it shouldn't block because `tryReadMVar`doesn't empty the `MVar`. I agree this design could be improved though!

2019-04-06 00:16 UTC, mhuesch reviewed
I don't want to block merge since this has been a long-running issue and is great work, modulo a few things I'd like to see tweaked.

Happy to have these go in a separate PR, if we decide their good suggestions.

2019-04-06 00:16 UTC, mhuesch commented on app/Features/Blockchain.hs
> +    let pm = ProtocolMagic (gdProtocolMagicId genesisData) RequiresNoMagic
I think this was added after you started the PR, but you could grab the `ProtocolMagic` out of `Genesis.Config` using https://github.com/input-output-hk/cardano-ledger/blob/8ef7bf8049bbcd201ef19c4038ae42ed79722be6/src/Cardano/Chain/Genesis/Config.hs#L161

2019-04-06 00:16 UTC, mhuesch commented on app/Features/Blockchain.hs
> +        , currentUTxOSize       = liftIO $ tryReadMVar utxoSizeVar
I _think_ this could be significantly simplified if a Queue datatype (e.g. [`TBQueue`](https://www.stackage.org/haddock/lts-13.4/stm-2.5.0.0/Control-Concurrent-STM-TBQueue.html)) were used instead of an MVar. That approach would also eliminate the need for an initial dummy value, since the queue could just be initialized as empty.

2019-04-06 00:16 UTC, mhuesch commented on app/Main.hs
> +          utxoSizeAfterBlockLoop lgTrace
This retry logic could be cut out and a simple blocking read used, such as [`readTBQueue`](https://www.stackage.org/haddock/lts-13.4/stm-2.5.0.0/Control-Concurrent-STM-TBQueue.html#v:readTBQueue)

This should address Ru's concern about MVar coordination to avoid deadlock, also.

2019-04-06 00:16 UTC, mhuesch commented on src/Cardano/Chain/Block/Validation.hs
> +              _ <- liftIO $ takeMVar sizeMVar
I think a Queue datatype (see my other comment) would clean this up. It would remove the concern about synchronization & deadlocks. If, for example, write was missed, or a read was missed, neither end would get "stuck".

2019-04-06 00:16 UTC, mhuesch commented on src/Cardano/Chain/Common/NetworkMagic.hs
> +parseReqNetworkMag _                    = RequiresMagic
Ack. Is there not a more-typed way to do this? Granted, that probably requires changes `cardano-shell` datatypes.

At the very least, I think we could explicitly match both cases and signal an error somehow (`panic` perhaps) on unrecognized input.

2019-04-06 00:16 UTC, mhuesch commented on test/Test/Cardano/Chain/Config.hs
> -mainnetEpochSlots = EpochSlots 21600
Assuming this was moved from `test/` because it was needed in the `src/` tree.

2019-04-06 00:16 UTC, mhuesch commented on stack.yaml
> -  - haskell-src-exts-1.21.0
Do we want to get rid of this?

2019-04-06 00:16 UTC, mhuesch commented on src/Cardano/Chain/Block/Validation.hs
> +  ABOBBlock    block -> updateBlock config c block
👍

2019-04-06 00:16 UTC, mhuesch commented on src/Cardano/Chain/Block/Validation.hs
> +  deriving Show
It would be nice to add a docstring, something like
```
-- | Size of a heap value, in words
```

2019-04-06 00:16 UTC, mhuesch commented on src/Cardano/Chain/Block/Validation.hs
> +  deriving Show
It would be nice to add a docstring, something like
```
-- | Number of entries in the UTxO
```

2019-04-06 04:07 UTC, erikd commented on app/Main.hs
> +          utxoSizeAfterBlockLoop lgTrace
Possibly doesn't even need a `TBQueue`, a `TVar` should do the trick as well and avoid `MVar` deadlocks.

2019-04-08 13:08 UTC, Jimbo4350 commented on app/Main.hs
> +          utxoSizeAfterBlockLoop lgTrace
I will do some investigation here and submit a follow up PR.

2019-04-08 13:10 UTC, Jimbo4350 commented on src/Cardano/Chain/Common/NetworkMagic.hs
> +parseReqNetworkMag _                    = RequiresMagic
Totally agree. We need to reconcile the [`CardanoConfiguration`](https://github.com/input-output-hk/cardano-shell/blob/develop/src/Cardano/Shell/Constants/Types.hs#L36) type with the `Config` type that exists in `cardano-ledger`. I'll raise an issue in both repos and link them.

2019-04-08 13:20 UTC, Jimbo4350 commented on test/Test/Cardano/Chain/Config.hs
> -mainnetEpochSlots = EpochSlots 21600
It made more sense to be in `src/` imo

2019-04-08 13:24 UTC, Jimbo4350 commented on stack.yaml
> -  - haskell-src-exts-1.21.0
I missed this, thanks for pointing it out!

2019-04-08 13:37 UTC, mhuesch commented on src/Cardano/Chain/Common/NetworkMagic.hs
> +parseReqNetworkMag _                    = RequiresMagic
Sounds good 👍

2019-04-08 14:19 UTC, mhuesch commented on app/Main.hs
> +          utxoSizeAfterBlockLoop lgTrace
To check my understanding of the various STM constructs: `TVar` would enforce coupling between the size-logger and the size-printer processes. Whereas `TBQueue` would give them a buffer to get slightly out of sync with each other. Is that right @erikd?

In this case it seems there's no harm in them being in sync.

2019-04-08 14:20 UTC, mhuesch commented on app/Features/Blockchain.hs
> +        , currentUTxOSize       = liftIO $ tryReadMVar utxoSizeVar
If we use a TVar we would still require a dummy value, as well.

2019-04-08 14:25 UTC, mhuesch commented
bors r+

2019-04-08 15:00 UTC, merged