Log UTxO-related stats at debug level during epoch validation
input-output-hk/cardano-ledger-byron pull request #472
Opened 2019-05-06 20:54 UTC by intricate

Probably a good idea to only computer and log `UTxO`-related stats at the `Debug` level.

2019-05-06 20:56 UTC, intricate commented on configuration/log-configuration.yaml
> +minSeverity: Info
Instead of doing this, as @CodiePP has pointed out to me, I could also specifically set the `SubTrace` value for the `cardano.epoch-validation.utxo-stats` logger to `NoTrace`. 

Would this be preferable to changing the global `minSeverity`?

2019-05-06 21:03 UTC, intricate commented on configuration/log-configuration.yaml
> +minSeverity: Info
In this case, we'd just have to change the `SubTrace` value for `cardano.epoch-validation.utxo-stats` to `Neutral` in order to resume logging again. Can do this by either manually editing the log configuration file or via the logging configuration web editor (default URL: http://localhost:12787).

2019-05-07 09:40 UTC, ruhatch requested changes

2019-05-07 09:40 UTC, ruhatch commented on src/Cardano/Chain/Epoch/Validation.hs
> +    cvs'
I think `do`-notation might be cleaner here

2019-05-07 09:40 UTC, ruhatch commented on src/Cardano/Chain/Epoch/Validation.hs
>      sizePair = calcUTxOSize (cvsUtxo cvs')
You can just pattern-match, rather than using `fst` and `snd`!

2019-05-07 09:40 UTC, ruhatch commented on configuration/log-configuration.yaml
> +minSeverity: Info
Yeah, I think it would be better to leave this as is and put `NoTrace` on the UTxO value - you should add some documentation somewhere about how to change this value too!

2019-05-07 16:30 UTC, ruhatch approved these changes
Looks great :)

2019-05-07 16:41 UTC, intricate commented
bors r+

2019-05-07 17:07 UTC, merged