[#429] Configuration conversion function
input-output-hk/cardano-ledger-byron pull request #533
Opened 2019-05-31 18:22 UTC by Jimbo4350

Closes #429

2019-06-03 14:16 UTC, ruhatch requested changes
Looks good, but a few changes to bring it in line with the rest of the codebase

2019-06-03 14:16 UTC, ruhatch commented on src/Cardano/Chain/Conversion.hs
> +-- | This module converts `CardanoConfiguration` to `Genesis.Config`
You can move this to the line about `module ... where` to get this as an actual module header in Haddock

2019-06-03 14:16 UTC, ruhatch commented on src/Cardano/Chain/Conversion.hs
> +  -> EitherT ConfigurationError IO Config
I think I'd prefer if we used `MonadError` to remain consistent with the rest of the codebase

2019-06-03 14:16 UTC, ruhatch commented on src/Cardano/Chain/Conversion.hs
> +  -> EitherT ConfigurationError IO Config
Then you can also make use of `wrapError`, which we use in the validation rules a lot

2019-06-03 14:16 UTC, ruhatch commented on src/Cardano/Chain/Conversion.hs
> +      $ hoistEither (lovelacePortionFromDouble $ teRichmenShare shellTestNetBal)
So this would become:
```haskell
    rMenShare <- lovelacePortionFromDouble (teRichmenShare shellTestNetBal)
      `wrapError` ConfigPortionConvErr
```

2019-06-03 14:16 UTC, ruhatch commented on src/Cardano/Chain/Genesis/Config.hs
> +      liftEither . first ConfigurationGenesisDataError =<< runExceptT
Can use `wrapError` here too :)

2019-06-03 14:16 UTC, ruhatch commented on src/Cardano/Chain/Genesis/Config.hs
> +      liftEither . first ConfigurationGenesisDataError =<< runExceptT
You would have to `<$>` it over the `IO` though

2019-06-03 14:16 UTC, ruhatch commented on src/Cardano/Chain/Genesis/Config.hs
> +    unGenesisHash genesisHash
Looks like you're already checking this in `mkConfigFromFile`, so you can remove this

2019-06-03 14:16 UTC, ruhatch commented on stack.yaml
> +  - transformers-either-0.1.1
Should be able to remove this if you switch to `MonadError` :)

2019-06-03 14:16 UTC, ruhatch commented on stack.yaml
> +  - tasty-hedgehog-1.0.0.1
I guess you should rebase on master as this is already updated

2019-06-03 14:16 UTC, ruhatch commented on test/Test/Cardano/Chain/Config.hs
> +  genHash <-
I think this is just
```
let genHash = either (panic . sformat build . Genesis.GenesisHashDecodeError) identity (decodeAbstractHash ...)
```

2019-06-04 12:40 UTC, ruhatch approved these changes
LGTM!

2019-06-04 21:17 UTC, mhuesch requested changes
2 issues that I see (noted in line-comments):

1. `ppUpdateProposalTTL` has been changed in a breaking way
2. I'm unclear on the story of `cardano-shell`

@Jimbo4350 it might be best to talk this over synchronously - perhaps in the core team meeting.

2019-06-04 21:17 UTC, mhuesch commented on src/Cardano/Chain/Common/NetworkMagic.hs
> -parseReqNetworkMag _                    = RequiresMagic
👍

2019-06-04 21:17 UTC, mhuesch commented on src/Cardano/Chain/Conversion.hs
> +
This looks great 🙌

2019-06-04 21:17 UTC, mhuesch commented on src/Cardano/Chain/Genesis/Config.hs
> +    mkConfigFromFile rnm fp expectedHash
Is the removal of the `confDir` argument possible because `fp` is a full path instead of a filename?

2019-06-04 21:17 UTC, mhuesch commented on src/Cardano/Chain/Genesis/Config.hs
> +  | ConfigGenSpecConvErr Text
Given that all the other constructors have Haddock fields, it would be nice if these all did too.

2019-06-04 21:17 UTC, mhuesch commented on src/Cardano/Chain/Genesis/NonAvvmBalances.hs
> +      (`wrapError` NonAvvmBalancesLovelaceError)
This is a little pedantic, but this block is indented by 4 spaces and could be outdented to just 2 spaces, for consistency with the surrounding code.

2019-06-04 21:17 UTC, mhuesch commented on src/Cardano/Chain/Update/ProtocolParameters.hs
> +  -- the slot up to which a proposal has to gather a majority of votes. If a
This seems unrelated to the Config conversion function, and significant. Are we indeed changing the interpretation of this field, to be an absolute `FlatSlotId`? Why is it bundled into this PR?

This seems to be at odds with the [main source-code usage of `ppUpdateProposalTTL`](https://github.com/input-output-hk/cardano-ledger/blob/e5d6844bc64bb6e720044511d74f6541964fe510/src/Cardano/Chain/Update/Validation/Interface.hs#L305) (param `u` comes from [here](https://github.com/input-output-hk/cardano-ledger/blob/e5d6844bc64bb6e720044511d74f6541964fe510/src/Cardano/Chain/Update/Validation/Interface.hs#L360)) which does filtering relative to the current slot. That should change if we're changing from relative to absolute.

This change also seems inconsistent all the other uses of `ppUpdateProposalTTL`:
https://github.com/input-output-hk/cardano-ledger/blob/e5d6844bc64bb6e720044511d74f6541964fe510/src/Cardano/Chain/Update/ProtocolParametersUpdate.hs#L60
https://github.com/input-output-hk/cardano-ledger/blob/e5d6844bc64bb6e720044511d74f6541964fe510/test/Test/Cardano/Chain/Elaboration/Block.hs#L227
https://github.com/input-output-hk/cardano-ledger/blob/e5d6844bc64bb6e720044511d74f6541964fe510/test/Test/Cardano/Chain/Genesis/Dummy.hs#L126

2019-06-04 21:17 UTC, mhuesch commented on src/Cardano/Chain/Update/ProtocolParameters.hs
> +  -- the slot up to which a proposal has to gather a majority of votes. If a
It also seems at odds with [the definition in `cardano-shell`](https://github.com/input-output-hk/cardano-shell/blob/44fa2129e07668ebc620708c3a83913cff6fff7c/src/Cardano/Shell/Presets.hs#L256) (documented [here](https://github.com/input-output-hk/cardano-shell/blame/44fa2129e07668ebc620708c3a83913cff6fff7c/configuration.md#L44)), so I'm wondering what motivated the change, or if it was an accident.

2019-06-04 21:17 UTC, mhuesch commented on src/Cardano/Chain/Genesis/Config.hs
>        (readGenesisData fp)
I didn't think much of this on the first read-through, but now I am wondering -

My understanding of the point of `cardano-shell` was that once it was done, we wouldn't need JSON decoders in `cardano-ledger` anymore. We would do something more like pure datatype-to-datatype conversion, with no parsing and e.g. the possibility of `read` failing on a numeric field.

The way things are set up in this PR, it seems like all that `cardano-shell` has done is introduced another layer of parsing and serialization. We still have the old JSON decoding logic, but we now have a new layer between us and the on-disk configuration. It is unclear to me that this is at all better - it actually seems worse.

2019-06-04 21:52 UTC, erikd commented on src/Cardano/Chain/Conversion.hs
> +  -> EitherT ConfigurationError IO Config
`MonadError` and `ExceptT` are basically isomorphic, but `MonadError` uses names like`throwError` and `catchError` that are easily confused with `throw`/`catch` used with exceptions.

I prefer the `EitherT` or `ExceptT` approach because the types are explicit, and using the combinator functions in `transformers-either`  handling errors in a principled way is super convenient.

However since the rest of the code base uses `MonadError` (with its poorly chosen method names) we should use that.

2019-06-05 00:56 UTC, mhuesch reviewed
Added additional notes - the major issues are resolved, but the minor tweaks still stand.

2019-06-05 00:56 UTC, mhuesch commented on src/Cardano/Chain/Update/ProtocolParameters.hs
> +  -- the slot up to which a proposal has to gather a majority of votes. If a
Ah. I was thrown off by the change of "number of slots" to "slot up to which". The above comments can be ignored.

I suggest we change that back, and maybe clarify that this `FlatSlotId` is a delta (to be added to / subtracted from an absolute slot), rather than an absolute index of a slot.

```suggestion
  -- the number of slots a proposal has to gather a majority of votes. If a
```

2019-06-05 00:56 UTC, mhuesch commented on src/Cardano/Chain/Genesis/Config.hs
>        (readGenesisData fp)
After talking this over in our meeting, and then revisiting & rereading the code, I think the current situation is fine. The benefit of `cardano-shell` seems to be less obvious from `cardano-ledger`'s point of view, because most of our config is stuck in the genesis block (thus stuck as JSON) and so we have to keep the `FromJSON` instances around to extract things.

I imagine (but I haven't checked yet) that the other parts of the project (e.g. `ouroboros-consensus` and `ouroboros-network` have greater apparent benefit from `cardano-shell` having factored out the configuration (thus insulating them from it).

2019-06-05 00:56 UTC, mhuesch commented on src/Cardano/Chain/Conversion.hs
> +convertConfig
```suggestion
--   This function mostly relies on FromJSON parsing, because much of `Config` originates from
--   data locked in the genesis block as JSON. Sadly, this means that `cardano-ledger` can't
--   benefit as much from `cardano-shell`'s function as an insulating layer around config &
--   parsing.
convertConfig
```

In keeping with my comment below [here](https://github.com/input-output-hk/cardano-ledger/pull/533/files#r290500402), I'd suggest adding something vaguely like this as documentation.

2019-06-06 12:24 UTC, Jimbo4350 commented on src/Cardano/Chain/Update/ProtocolParameters.hs
> +  -- the slot up to which a proposal has to gather a majority of votes. If a
Agreed, I think there was a miscommunication on slack. Good catch!
https://input-output-rnd.slack.com/archives/CCZSDE005/p1559143010050200

2019-06-06 12:45 UTC, Jimbo4350 commented on src/Cardano/Chain/Conversion.hs
> +convertConfig
I think as it stands now we generate the mainnet config this way, but I think in the future for generating testnet configs we would use `CardanoConfiguration`.

2019-06-06 14:36 UTC, mhuesch commented on src/Cardano/Chain/Conversion.hs
> +convertConfig
Mainnet will always depend on the JSON locked in the genesis block, though, so the point still stands. But we could add a caveat that it only applies to mainnet.

2019-06-06 14:38 UTC, mhuesch commented on src/Cardano/Chain/Genesis/Config.hs
> +    mkConfigFromFile rnm fp expectedHash
Jordan says:

> I think as it is now, you would have to specify the full path in `CardanoConfiguration`
> 
> This simplifies thing imo

2019-06-06 14:42 UTC, Jimbo4350 commented on src/Cardano/Chain/Genesis/Config.hs
> +    mkConfigFromFile rnm fp expectedHash
Currently you would have to specify the full path in `CardanoConfiguration` and this simplifies things imo.

2019-06-06 14:47 UTC, mhuesch approved these changes
LGTM :shipit:

2019-06-06 14:47 UTC, mhuesch commented on src/Cardano/Chain/Conversion.hs
> +convertConfig
👍

2019-06-07 22:19 UTC, Jimbo4350 commented
bors r+

2019-06-07 22:40 UTC, merged