Implement multiple validation modes
input-output-hk/cardano-ledger-byron pull request #548
Opened 2019-06-11 21:34 UTC by intricate

2019-06-11 22:17 UTC, erikd commented on cardano-ledger/src/Cardano/Chain/Block/Validation.hs
>    case (cvsPreviousHash cvs, boundaryPrevHash bvd) of
I think those are important enough and cheap enough to check in all validation modes.

2019-06-11 22:19 UTC, erikd commented on cardano-ledger/src/Cardano/Chain/Block/Validation.hs
> +  --             'DelegationValidationMode'?
Surely there are some things that are serious enough to warrant being an error in all block validation modes.

2019-06-11 22:25 UTC, intricate commented on cardano-ledger/src/Cardano/Chain/Block/Validation.hs
> +  --             'DelegationValidationMode'?
Perhaps so but I'm only questioning this because of Edsko's explanation in this issue: https://github.com/input-output-hk/ouroboros-network/issues/440

>```
>      -- | Apply a previously applied block
>      --
>      -- Since a block can only be applied to a single, specific, ledger state,
>      -- if we apply a previously applied block again it will be applied in the
>      -- very same ledger state, and therefore can't possibly fail.
>      --
>      -- NOTE: During testing it might be useful to implement 'ledgerDbReapply'
>      -- using the code that /does/ do all checks, and throw an exception if
>      -- any of them fail (as this would indicate a bug in the code somewhere).
>      -- We do not have sufficient context in the ledger DB to /verify/ that
>      -- when we reapply a block we are applying it to the correct ledger.
>    , ldbConfReapply :: b -> l -> l
>```

Specifically,
>it will be applied in the very same ledger state, and therefore can't possibly fail.

2019-06-11 22:26 UTC, erikd commented on cardano-ledger/src/Cardano/Chain/Block/Validation.hs
> +    --             remininding us to utilize it in the future, if necessary.
Probably worth asking about that. If that validation does not return any errors its not complete.

2019-06-11 22:26 UTC, erikd commented on cardano-ledger/test/Test/Cardano/Chain/Elaboration/Block.hs
> +    , Update.ppMaxHeaderSize    = 569 * pps ^. maxHdrSz
What are these changes about?

2019-06-11 22:29 UTC, erikd commented on cardano-ledger/src/Cardano/Chain/Block/Validation.hs
> +  --             'DelegationValidationMode'?
Ok, but after applying a whole bunch of blocks without any validation, it should still check that at the end the chain the hash should still match a fully validated chain.

Probably worth adding a comment about that (if there isn't one already).

2019-06-11 22:33 UTC, intricate commented on cardano-ledger/test/Test/Cardano/Chain/Elaboration/Block.hs
> +    , Update.ppMaxHeaderSize    = 569 * pps ^. maxHdrSz
I'll have to add a comment explaining these. These seem to be the minimum constant multipliers that I can use for size limits such that all tests still pass without returning "block too large" or "block header too large" errors.

2019-06-11 22:34 UTC, intricate commented on cardano-ledger/test/Test/Cardano/Chain/Elaboration/Block.hs
> +    , Update.ppMaxHeaderSize    = 569 * pps ^. maxHdrSz
I'll have to add a comment explaining these. These seem to be the minimum constant multipliers that I can use for elaborating abstract size limits such that all tests still pass without returning "block too large" or "block header too large" errors.

2019-06-12 03:39 UTC, intricate commented on cardano-ledger/test/Test/Cardano/Chain/Elaboration/Update.hs
> +  -- FIXME @intricate: Fields that I'm not sure about, I'm just using
Actually, I'm not sure that any of the fields I'm copying from `dummyProtocolParameters` are even relevant to the tests that I've added. I can probably just initialize them all to `0` or something.

2019-06-12 03:39 UTC, intricate commented on cardano-ledger/test/Test/Cardano/Chain/UTxO/ValidationMode.hs
> +      let pm = Dummy.aProtocolMagic
Will address these `Dummy.aProtocolMagic`s tomorrow.

2019-06-12 03:40 UTC, intricate commented on cardano-ledger/test/Test/Cardano/Chain/Block/Model.hs
> +    -- @intricate: Hardcoded BlockValidate
I think hardcoding `BlockValidate` here is fine. Will remove comments such as this as well.

2019-06-12 03:44 UTC, intricate commented on cardano-ledger/test/Test/Cardano/Chain/UTxO/ValidationMode.hs
> +        Range.constant 156789 -- @intricate
Tagged myself on lines containing this `156789` "magic number" to remind myself to come back and rethink this. `15689` isn't really significant other than the fact that it "just worked" as a minimum bound. Will take a look and improve this generator tomorrow.

2019-06-12 06:06 UTC, dnadales commented
I'm a bit confused by this, so sorry for the silly question:

> There should be three scenarios: NewSignal/NewState, OldSignal/NewState, OldSignal/OldState

Do we care about these scenarios? I thought this was about checking whether we would perform validation or not when applying a block.

2019-06-12 06:07 UTC, dnadales commented on cardano-ledger/test/Test/Cardano/Chain/UTxO/ValidationMode.hs
> +        Range.constant 156789 -- @intricate
Great. Whatever constant we choose, we should document why we chose it :D

2019-06-12 06:13 UTC, dnadales commented on cardano-ledger/src/Cardano/Chain/Block/ValidationMode.hs
> +-- | Perform an action only when in the 'BlockValidate' mode. Otherwise, do
Why not using `Control.Monad.when` with the predicate `mode == BlockValidate`?

But regardless of this, we are seeing a lot of patterns of the form

```haskell
whenBlockValidate mode (cond `orThrowError` err)
```

Isn't it better to define a function like `check mode cond err`?

Something a bit more controversial could be making the block validation functions and `check` a reader monad, so that we don't have to pass the mode everywhere :man_shrugging:

2019-06-12 06:14 UTC, dnadales commented on cardano-ledger/src/Cardano/Chain/Block/ValidationMode.hs
> +  | BlockRevalidate
Revalidate here seems to hint at the fact that we're performing the validations again :)

2019-06-12 08:57 UTC, ruhatch requested changes
Okay, so quite a few changes here, but the general structure is good.

2019-06-12 08:57 UTC, ruhatch commented on cardano-ledger/src/Cardano/Chain/Block/Validation.hs
>    case (cvsPreviousHash cvs, boundaryPrevHash bvd) of
:heavy_plus_sign:

2019-06-12 08:57 UTC, ruhatch commented on cardano-ledger/src/Cardano/Chain/Block/Validation.hs
> +  --             'DelegationValidationMode'?
Just pass the `BlockValidationMode` here I think

2019-06-12 08:57 UTC, ruhatch commented on cardano-ledger/src/Cardano/Chain/Block/Validation.hs
> +    --             remininding us to utilize it in the future, if necessary.
The validation in that one cannot fail, so I'd say take it out of `MonadError` and just make it return `State`. Then here, it's just `pure $ UPI.registerEpoch ...`

2019-06-12 08:57 UTC, ruhatch commented on cardano-ledger/src/Cardano/Chain/Block/ValidationMode.hs
> +  | BlockRevalidate
Indeed, I think `BlockValidation | NoBlockValidation` might work here

2019-06-12 08:57 UTC, ruhatch commented on cardano-ledger/src/Cardano/Chain/Block/ValidationMode.hs
> +-- | Perform an action only when in the 'BlockValidate' mode. Otherwise, do
In this case, as the priority is readability of the predicates, I think a `MonadReader BlockValidationMode m` would actually work pretty well. You could add an:
```
orThrowErrorBVM :: (MonadError e m, MonadReader BlockValidationMode m) => Bool -> e -> m ()
orThrowErrorBVM condition e = do
  bvm <- ask
  unless (bvm == NoBlockValidation || condition) (throwError e)

infix 1 `orThrowError`
```
resulting in e.g.
```
  blockProtocolMagicId b == configProtocolMagicId config
    `orThrowErrorBVM` ChainValidationProtocolMagicMismatch
                        (blockProtocolMagicId b)
                        (configProtocolMagicId config)
```

2019-06-12 08:57 UTC, ruhatch commented on cardano-ledger/src/Cardano/Chain/Block/ValidationMode.hs
> +-- | Perform an action only when in the 'BlockValidate' mode. Otherwise, do
@dnadales is that what you had in mind too?

2019-06-12 08:57 UTC, ruhatch commented on cardano-ledger/src/Cardano/Chain/UTxO/ValidationMode.hs
> +  = TxValidate
I think `TxValidation | TxValidationNoCrypto | NoTxValidation` might be clearer

2019-06-12 08:57 UTC, ruhatch commented on cardano-ledger/src/Cardano/Chain/UTxO/Validation.hs
> +        (uncurry $ validateWitness tvmode pmi sigData)
I don't think you need to pass the mode here, because you're already using it above

2019-06-12 08:57 UTC, ruhatch commented on cardano-ledger/src/Cardano/Chain/UTxO/Validation.hs
> +validateTxIn TxRevalidateSameState _ _ = pure ()
If you're using `TxRevalidateSameState`, you'll never call this function anyway, so you should be able to drop the arg here

2019-06-12 08:57 UTC, ruhatch commented on cardano-ledger/src/Cardano/Chain/UTxO/Validation.hs
> +  => TxValidationMode
You should be able to drop the arg here too

2019-06-12 08:57 UTC, ruhatch commented on cardano-ledger/src/Cardano/Chain/UTxO/Validation.hs
> +        (uncurry $ validateWitness tvmode pmi sigData)
In `whenTxValidate` that is

2019-06-12 08:57 UTC, ruhatch commented on cardano-ledger/test/Test/Cardano/Chain/Block/Model.hs
> +    -- @intricate: Hardcoded BlockValidate
Yeah, definitely what we want here

2019-06-12 08:57 UTC, ruhatch commented on cardano-ledger/test/Test/Cardano/Chain/Block/Model.hs
> +    -- @intricate: Hardcoded BlockValidate
You can even push it into `elaborateAndUpdate` considering you're hardcoding it anyway

2019-06-12 08:57 UTC, ruhatch commented on cardano-ledger/test/Test/Cardano/Chain/Block/Validation.hs
> +          ABOBBlock block -> updateBlock bvmode config c block
Again, I'd say do the hardcoding here at the `updateBlock` call site and avoid polluting the rest of the logic

2019-06-12 08:57 UTC, ruhatch commented on cardano-ledger/test/Test/Cardano/Chain/Block/ValidationMode.hs
> +    sscProof <- Gen.choice
I'd say drop this if you're not using it and change below to be an update, rather than construction

2019-06-12 08:57 UTC, ruhatch commented on cardano-ledger/test/Test/Cardano/Chain/Block/ValidationMode.hs
> +      (\(Annotated _ bs) -> Annotated
So `\(Annotated p bs) -> Annotated (p { record update}) bs`

2019-06-12 08:57 UTC, ruhatch commented on cardano-ledger/test/Test/Cardano/Chain/UTxO/ValidationMode.hs
> +-- Concrete Generators
So as a general comment these generators are going to have really poor shrinking. This is exactly how I defined them the first time round in the abstract generators, but they suffer from using the `Monad Gen` instance, as outlined in Edsko's blog post. I think it would be better to use the abstract generators that I made in `cardano-ledger-specs` as those have good manual shrinking. Please come to me if you're having difficulties adapting those.

2019-06-12 08:57 UTC, ruhatch commented on cardano-ledger/src/Cardano/Chain/Epoch/Validation.hs
> +      $ updateChainBlockOrBoundary bvmode config cvs block
I think this is a case where we're only ever going to run it in `BlockValidate` mode, so you can probably hardcode it right here, and remove the parameter passing from the other functions here.

2019-06-12 08:57 UTC, ruhatch commented on cardano-ledger/src/Cardano/Chain/UTxO/ValidationMode.hs
> +whenTxValidateOrRevalidate
I'm not sure you ever use this one, so maybe get rid of it if you don't need it. Someone else can always define it if we need it later on.

2019-06-12 10:24 UTC, dnadales commented on cardano-ledger/src/Cardano/Chain/Block/ValidationMode.hs
> +-- | Perform an action only when in the 'BlockValidate' mode. Otherwise, do
@ruhatch that was exactly what I had in mind :man: :zap:  :man:

2019-06-12 14:04 UTC, intricate commented on cardano-ledger/src/Cardano/Chain/UTxO/ValidationMode.hs
> +whenTxValidateOrRevalidate
Oops

2019-06-12 15:33 UTC, intricate commented on cardano-ledger/src/Cardano/Chain/UTxO/Validation.hs
> +        (uncurry $ validateWitness tvmode pmi sigData)
@ruhatch You're right but I wasn't sure if, for some reason, in the future, someone may want to test these individual functions with different `ValidationMode`s. Does that make sense or am I perhaps overthinking it?

2019-06-12 15:43 UTC, intricate commented on cardano-ledger/test/Test/Cardano/Chain/Block/ValidationMode.hs
> +      (\(Annotated _ bs) -> Annotated
:man_facepalming: oops.

2019-06-13 17:41 UTC, ruhatch commented on cardano-ledger/src/Cardano/Chain/Block/ValidationMode.hs
> +-- | Perform an action only when in the 'BlockValidate' mode. Otherwise, do
@intricate To make it clearer I think `orThrowErrorInBlockValidationMode` is better. Even though it seems crazy long, it's just more descriptive, so:
```
  blockProtocolMagicId b == configProtocolMagicId config
    `orThrowErrorInBlockValidationMode`
      ChainValidationProtocolMagicMismatch
        (blockProtocolMagicId b)
        (configProtocolMagicId config)

2019-06-14 02:36 UTC, erikd commented on cardano-ledger/src/Cardano/Chain/Block/Validation.hs
> +  -> ValidationModeT Error ValidationModeEnv ResIO UTxO
Wow, is that type for real???

2019-06-14 02:37 UTC, erikd commented on cardano-ledger/src/Cardano/Chain/Block/Validation.hs
> +  (pure (hoist (withExceptT ErrorParseError) blocks))
Something about `pure` and `hoist` being used like that strikes me as odd. Its almost as if you need a transformers version of `Control.Monad.join`.

2019-06-14 02:43 UTC, erikd commented on cardano-ledger/src/Cardano/Chain/Epoch/Validation.hs
> +  pure (pure (hoist (withExceptT EpochParseError) blocks))
Like above, `pure . pure . hoist` seems weird.

2019-06-14 02:46 UTC, erikd commented on cardano-ledger/src/Cardano/Chain/UTxO/Validation.hs
>    => Environment
@ruhatch @dnadales Here we have `Environment` being passed in as a parameter and `ValidationModeEnv` being passed as a `MonadReader`. Was this suggested by either of you? If so why? I don't seem the sense of having two bits of data with essentially the same purpose being passed into the function in two such different ways.

2019-06-14 02:47 UTC, erikd commented on cardano-ledger/src/Cardano/Chain/Update/Validation/Interface.hs
> +  -> State
Here, the code used to be able to return an error and now can't? Why is that?

2019-06-14 02:51 UTC, erikd commented on cardano-ledger/src/Cardano/Chain/ValidationMode.hs
> +  -> m ()
This is beginning to look like the old code base.

2019-06-14 02:53 UTC, erikd commented on cardano-ledger/src/Cardano/Chain/ValidationMode.hs
> +type ValidationModeT e r m a = ExceptT e (ReaderT ValidationModeEnv m) a
If you drop the `r` from that, then I think `ValidationModeT e ValidationModeEnv m a` can be changed to `ValidationModeT e m a` which is a definite improvement.

2019-06-14 02:54 UTC, intricate commented on cardano-ledger/src/Cardano/Chain/Update/Validation/Interface.hs
> +  -> State
https://github.com/input-output-hk/cardano-ledger/pull/548#discussion_r292792803

This function, `registerEpoch`, was never actually returning an error in any case.

2019-06-14 02:58 UTC, intricate commented on cardano-ledger/src/Cardano/Chain/ValidationMode.hs
> +type ValidationModeT e r m a = ExceptT e (ReaderT ValidationModeEnv m) a
That `r` must have been a mistake. Oops.

2019-06-14 03:06 UTC, intricate commented on cardano-ledger/src/Cardano/Chain/UTxO/Validation.hs
>    => Environment
Personally, I think I'd rather drop these `MonadReader` changes and pass the appropriate `*ValidationMode` either as a separate argument or via an appropriate field within any of the relevant `Environment` data types.

2019-06-14 07:22 UTC, dnadales commented on cardano-ledger/src/Cardano/Chain/UTxO/Validation.hs
>    => Environment
@erikd see https://github.com/input-output-hk/cardano-ledger/pull/548#discussion_r292799340 for context. Basically the idea was so preserve the readability of the predicates. 

The Environment argument refers to the environment of the operational rules. 

>  I don't seem the sense of having two bits of data with essentially the same purpose being passed into the function in two such different ways.

Is a consequence of this the fact that monad readers should not take any arguments?

But in any case if you don't want to have a monad reader feel free to revert it back. But as far as I understand the validation mode *should not* be in the environment since this is the environment in the spec, and we want it to be as close as possible to the latter.

@ruhatch : thoughts?

2019-06-14 13:00 UTC, intricate commented on cardano-ledger/src/Cardano/Chain/UTxO/Validation.hs
>    => Environment
> But as far as I understand the validation mode _should not_ be in the environment since this is the environment in the spec, and we want it to be as close as possible to the latter.

This makes sense. Didn't realize this.

2019-06-14 13:49 UTC, dnadales commented on cardano-ledger/src/Cardano/Chain/Block/Validation.hs
> +    runReaderT (UTxO.updateUTxO utxoEnv utxo txs) vModeEnv
Remember to check this.

2019-06-14 13:57 UTC, dnadales commented on cardano-ledger/src/Cardano/Chain/UTxO/Validation.hs
> +      `wrapError` UTxOValidationTxValidationError
What about:

```haskell
  whenTxValidationOrNoCrypto (validateTx env utxo aTx)
     `wrapError` UTxOValidationTxValidationError

whenTxValidationOrNoCrypto
  :: (MonadError TxValidationError m, MonadReader ValidationModeEnv m)
  => m ()
  -> m ()


```

2019-06-17 01:11 UTC, intricate commented on cardano-ledger/src/Cardano/Chain/UTxO/Validation.hs
> +      `wrapError` UTxOValidationTxValidationError
Turns out that `wrapError` doesn't play well with the results of our `when*Validation*` functions due to type constraints.

Here's the type sig for `wrapError`:
```
wrapError :: MonadError e' m => Either e a -> (e -> e') -> m a
```

I ended up having to write another version of `wrapError`, `wrapExceptTError` (open to suggestions for a better name) which I'm thinking should be in `cardano-prelude`:
```
wrapExceptTError :: MonadError e' m => ExceptT e m a -> (e -> e') ->  m a
```

I spent some time struggling to find some way of converting the error type in a `MonadError` but fell short. If we could find a nice way to do this, then we could rewrite `wrapError` in a more abstract way.

2019-06-17 01:17 UTC, intricate commented on cardano-ledger/src/Cardano/Chain/Block/Validation.hs
> +    runReaderT (UTxO.updateUTxO utxoEnv utxo txs) vModeEnv
I now remember why I used `runReaderT` here. `wrapError` accepts an `Either e a` parameter but the type of `updateUTxO` is `(MonadError UTxOValidationError m, MonadReader ValidationModeEnv m) => ... -> m UTxO` (notice the `MonadReader` constraint). There's no `MonadReader` instance for `Either` so, therefore, the result of a call to `updateUTxO` can't be passed to `wrapError`.

I think I was temporarily using `runReaderT` here while I worked out how I wanted to approach this issue.

2019-06-17 01:56 UTC, intricate commented on cardano-ledger/test/Test/Cardano/Chain/UTxO/ValidationMode.hs
> +        Range.constant 156789 -- @intricate
Followed @ruhatch's advice and removed these concrete generators as well as the property for which they were written, `ts_prop_updateUTxO_Invalid`.

2019-06-17 04:55 UTC, intricate commented on cardano-ledger/src/Cardano/Chain/ValidationMode.hs
> +wrapExceptTError :: MonadError e' m => ExceptT e m a -> (e -> e') ->  m a
@ruhatch @dnadales: Is it cool if I move this into `cardano-prelude` or do you guys perhaps have a more clever way of doing this?

2019-06-17 09:55 UTC, dnadales commented on cardano-ledger/src/Cardano/Chain/UTxO/Validation.hs
> +      `wrapError` UTxOValidationTxValidationError
I don't want to keep on adding more noise, so ignore my nonsense in favor of what you or @ruhatch think is more sensible.

I'd rather not have a `wrapExceptTError`, maybe `wrapError` should have a more general type in that case.

But if the problem is the type mismatch that you're getting, we could simply write:

```haskell
whenTxValidationOrNoCrypto $ 
    validateTx env utxo aTx  `wrapError` UTxOValidationTxValidationError
```

And regarding 

```haskell
whenTxValidationOrNoCrypto action = do
  tvmode <- askTVM
  case tvmode of
    NoTxValidation -> pure ()
    _              -> action

```

we might want to use `Control.Monad.when` instead of the `case` statement.

2019-06-17 09:55 UTC, dnadales commented on cardano-ledger/src/Cardano/Chain/ValidationMode.hs
> +wrapExceptTError :: MonadError e' m => ExceptT e m a -> (e -> e') ->  m a
See https://github.com/input-output-hk/cardano-ledger/pull/548#discussion_r294220544

2019-06-17 12:21 UTC, ruhatch requested changes

2019-06-17 12:21 UTC, ruhatch commented on cardano-ledger/src/Cardano/Chain/UTxO/Validation.hs
>    => Environment
Like @dnadales said these are two very different kinds of 'environment'. We want one to be very clearly in the types so it looks just like the spec and the other to be implicit in the `Reader`, because it's an optimisation.

2019-06-17 12:21 UTC, ruhatch commented on cardano-ledger/src/Cardano/Chain/ValidationMode.hs
> +data ValidationModeEnv = ValidationModeEnv
You can definitely just call this `ValidationMode` :)

2019-06-17 12:21 UTC, ruhatch commented on cardano-ledger/src/Cardano/Chain/ValidationMode.hs
> +  -> m ()
Not all `mtl` is evil ;)

2019-06-17 12:21 UTC, ruhatch commented on cardano-ledger/src/Cardano/Chain/ValidationMode.hs
> +  bvmode <- askBVM
Yeah, this can become:
```
bvmode <- askBVM
when (bvmode == BlockValidation) action
```

2019-06-17 12:21 UTC, ruhatch commented on cardano-ledger/src/Cardano/Chain/ValidationMode.hs
> +  case tvmode of
And this could be
```
tvmode <- askTVM
unless (tvmode == NoTxValidation) action
```

2019-06-17 12:21 UTC, ruhatch commented on cardano-ledger/src/Cardano/Chain/ValidationMode.hs
> +  case tvmode of
You could even rename the function to `unlessNoTxValidation`?

2019-06-17 12:21 UTC, ruhatch commented on cardano-ledger/src/Cardano/Chain/ValidationMode.hs
> +askBVM
I think I would prefer to put these in full `askBlockValidationMode`, at which point you might say, don't even bother with the helper function!

2019-06-17 12:21 UTC, ruhatch commented on cardano-ledger/src/Cardano/Chain/ValidationMode.hs
> +type ValidationModeT e m a = ExceptT e (ReaderT ValidationModeEnv m) a
I don't think we should define an extra transformer to be honest. It's masking the fact that there is an `ExceptT` inside and it's more obvious to have
```
(`runReaderT` validationMode) . runExceptT
```
as a reader (haha)

2019-06-17 12:21 UTC, ruhatch commented on cardano-ledger/src/Cardano/Chain/ValidationMode.hs
> +wrapExceptTError :: MonadError e' m => ExceptT e m a -> (e -> e') ->  m a
@intricate what about:
```
wrapErrorWithBlockValidationMode
  :: (MonadError e' m, MonadReader ValidationMode m) 
  => ReaderT ValidationMode (Either e a) 
  -> (e -> e') 
  -> m a
wrapErrorWithBlockValidationMode readerAction = do
  validationMode <- ask
  runReaderT readerAction validationMode >>= \case
    Left err -> throwError $ wrapper err
    Right x -> pure x
```

2019-06-17 12:21 UTC, ruhatch commented on cardano-ledger/src/Cardano/Chain/ValidationMode.hs
> +wrapExceptTError :: MonadError e' m => ExceptT e m a -> (e -> e') ->  m a
Let me know if there are any type errors with that, but I think it should work

2019-06-18 06:32 UTC, intricate commented on cardano-ledger/src/Cardano/Chain/ValidationMode.hs
> +type ValidationModeT e m a = ExceptT e (ReaderT ValidationModeEnv m) a
Alright, dropped the `ValidationModeT` type.

2019-06-18 06:46 UTC, intricate commented on cardano-ledger/src/Cardano/Chain/ValidationMode.hs
> +wrapExceptTError :: MonadError e' m => ExceptT e m a -> (e -> e') ->  m a
Thanks!

Only had to make a slight change to type sig

```
wrapErrorWithValidationMode
  :: (MonadError e' m, MonadReader ValidationMode m) 
  => ReaderT ValidationMode (Either e) a 
  -> (e -> e') 
  -> m a
```

2019-06-20 10:17 UTC, ruhatch approved these changes
Looks really good I think - worth several rounds of review :)

2019-06-20 10:18 UTC, ruhatch commented
bors r+

2019-06-20 10:25 UTC, merged