Add ToCBOR and FromCBOR instances for ChainValidationState
input-output-hk/cardano-ledger-byron pull request #569
Opened 2019-07-08 10:05 UTC by mrBliss

This requires `ToCBOR` and `FromCBOR` instances for a whole bunch of other types
too.

The consensus storage layer needs these instances in order to write/read snapshots of the ledger state to/from disk.

Roundtrip property tests and golden tests still need to be written. Can somebody of the ledger team do this? Feel free to push more commits to this PR.

 I tried to adhere to the existing style as much as I could, but I might have made some mistakes.

2019-07-08 10:40 UTC, mrBliss commented on cardano-ledger/src/Cardano/Chain/Block/Validation.hs
> +      <*> (Seq.fromList <$> fromCBOR)
I go through a list here because there are no `ToCBOR` and `FromCBOR` instances for `Seq`.

2019-07-08 10:41 UTC, mrBliss commented on cardano-ledger/src/Cardano/Chain/Common/Compact.hs
> +  fromCBOR = CompactAddress . BSS.toShort <$> fromCBOR
I go through a `ByteString` here because there are no `ToCBOR` and `FromCBOR` instances for `ShortByteString`.

2019-07-08 10:41 UTC, mrBliss commented on cardano-ledger/src/Cardano/Chain/Delegation/Map.hs
> +  fromCBOR = Map . Bimap.fromList <$> fromCBOR
I go through a `Map` here because there are no `ToCBOR` and `FromCBOR` instances for `Bimap`.

2019-07-08 10:41 UTC, mrBliss commented on cardano-ledger/src/Cardano/Chain/Delegation/Validation/Scheduling.hs
> +      <$> (Seq.fromList <$> fromCBOR)
I go through a list here because there are no `ToCBOR` and `FromCBOR` instances for `Seq`.

2019-07-08 12:14 UTC, dnadales approved these changes
LGTM

2019-07-08 12:26 UTC, dnadales commented
I've created [this issue](https://github.com/input-output-hk/cardano-ledger/issues/570) to add the tests.

2019-07-08 15:26 UTC, intricate requested changes
Looks good. Just a couple of concerns with what seem to be incorrect parameter values for some `enforceSize` and `encodeListLen` calls.

2019-07-08 15:26 UTC, intricate commented on cardano-ledger/src/Cardano/Chain/Common/Compact.hs
> +  fromCBOR = CompactAddress . BSS.toShort <$> fromCBOR
Seems sensible. I imagine it should be encoded/decoded in the same way as a regular `ByteString` anyways.

2019-07-08 15:26 UTC, intricate commented on cardano-ledger/src/Cardano/Chain/Block/Validation.hs
> +    encodeListLen 7
Why `encodeListLen 7` when we're only encoding 6 values? Same question goes for the `enforceSize "ChainValidationState" 7` call above.

2019-07-08 15:26 UTC, intricate commented on cardano-ledger/src/Cardano/Chain/Delegation/Validation/Scheduling.hs
> +    encodeListLen 2
Did you mean, `encodeListLen 3`?

2019-07-08 17:48 UTC, mrBliss commented on cardano-ledger/src/Cardano/Chain/Block/Validation.hs
> +    encodeListLen 7
> Why `encodeListLen 7` when we're only encoding 6 values? Same question goes for the `enforceSize "ChainValidationState" 7` call above.

Counting is hard :man_facepalming:

2019-07-08 17:49 UTC, mrBliss commented on cardano-ledger/src/Cardano/Chain/Delegation/Validation/Scheduling.hs
> +    encodeListLen 2
> Did you mean, `encodeListLen 3`?

Indeed, this is a copy-paste error. Another argument for using generics for this :slightly_smiling_face:

2019-07-08 17:50 UTC, mrBliss commented on cardano-ledger/src/Cardano/Chain/Delegation/Validation/Scheduling.hs
> +    encodeListLen 2
About `ShortByteString`: https://hackage.haskell.org/package/serialise-0.2.1.0/docs/src/Codec.Serialise.Class.html#line-358 made me think that maybe a more efficient implementation is possible.

2019-07-08 17:51 UTC, mrBliss commented
> Looks good. Just a couple of concerns with what seem to be incorrect parameter values for some `enforceSize` and `encodeListLen` calls.

Thanks for going over this. Those bugs are what you get when you don't test your code. I wouldn't wait too long with #570  :wink:

2019-07-08 17:53 UTC, mrBliss commented
Pushed my fixes for the bugs @intricate noticed.

2019-07-09 07:12 UTC, intricate commented
Note: I pushed a commit that includes a CBOR round-trip test for `SigningHistory`. There are still some more round-trips and goldens to implement.

2019-07-11 18:37 UTC, intricate approved these changes
LGTM. Just need to ensure we add round-trip and golden tests (issue #570) ASAP.

2019-07-11 20:53 UTC, intricate commented
bors r+

2019-07-11 21:11 UTC, merged