expose a function to update chain state without utxo
input-output-hk/cardano-ledger-byron pull request #684
Opened 2019-11-22 13:37 UTC by redxaxder

2019-11-22 19:41 UTC, dnadales approved these changes
Really nicely done!

2019-11-25 14:51 UTC, intricate approved these changes
LGTM.

However, I would instead `rebase` this branch on `master` instead of including the merge commit a9ee69061bd7a4e6a2ccf74ab707728fc2113f71.

2019-11-25 14:51 UTC, intricate commented on cardano-ledger/src/Cardano/Chain/Block/Validation.hs
> +data ChainValidationStateI b = ChainValidationStateI
Does the `I` suffix represent "internal"? Would `InternalChainValidationState` or `ChainValidationStateInternal` be too long of a name? This suggestion would also apply to other symbols suffixed with `I`.

Interested in your opinions as well @dnadales @mhuesch.

2019-11-25 14:51 UTC, intricate commented on cardano-ledger/src/Cardano/Chain/Block/Validation.hs
> +      , k          = configK config
I guess we could just change this to `k = configK config` (i.e. too much whitespace here since this isn't actually aligned with anything).

2019-11-25 14:51 UTC, intricate commented on cardano-ledger/src/Cardano/Chain/Block/Validation.hs
> +      { bUtxo        = cvsiUtxo cvs
Extra whitespace here. Perhaps just `bUtxo = cbsiUtxo cvs` unless we intend to align the `=`s here.

2019-11-25 14:51 UTC, intricate commented on cardano-ledger/src/Cardano/Chain/Block/Validation.hs
> +    }
Could align the `=`s here or remove the extra whitespace.

2019-11-28 13:45 UTC, intricate commented on cardano-ledger/src/Cardano/Chain/Block/Validation.hs
> +data ChainValidationStateI b = ChainValidationStateI
Spoke to @mhuesch about this on Slack and he agreed with me. I think using the full word `Internal` would make things a bit more clear.

2019-12-03 20:47 UTC, redxaxder commented
bors r+

2019-12-09 13:42 UTC, intricate requested changes
Would like to see a change here before approving:

https://github.com/input-output-hk/cardano-ledger/pull/684#discussion_r350217737

2020-01-29 13:31 UTC, dcoutts commented
As documented in #650 we've concluded that the wallet will take a different approach and will not need this functionality. So our code remains simpler if we don't include it.

2020-01-29 13:31 UTC, closed without merging