Change AProtocolMagic and ProtocolMagicId
input-output-hk/cardano-ledger-byron pull request #687
Opened 2019-11-27 15:47 UTC by redxaxder

2019-11-27 18:15 UTC, intricate requested changes

2019-11-27 18:15 UTC, intricate commented on crypto/src/Cardano/Crypto/ProtocolMagic.hs
> +  , getRequiresNetworkMagic  :: !RequiresNetworkMagic
Not a big deal, but the `::` might be over-indented here (there's an extra space).

2019-11-27 18:15 UTC, intricate commented on crypto/src/Cardano/Crypto/ProtocolMagic.hs
> +import Cardano.Binary (FromCBOR(..), ToCBOR(..), serialize', FromCBORAnnotated(..), withSlice', encodePreEncoded)
This line's too long and unsorted:

```suggestion
import Cardano.Binary 
  ( FromCBOR(..)
  , FromCBORAnnotated(..)
  , ToCBOR(..)
  , encodePreEncoded
  , serialize'
  , withSlice'
  )
```

2019-11-27 18:15 UTC, intricate commented on crypto/src/Cardano/Crypto/ProtocolMagic.hs
> +  where
```suggestion
 where
```

In `cardano-ledger`, `where`s have typically been indented like this:

https://github.com/input-output-hk/cardano-ledger/blob/48a69d7597d3eb26b47ba2fe65d3db381b27b5b0/cardano-ledger/src/Cardano/Chain/Block/Validation.hs#L388-L389

2019-11-27 18:15 UTC, intricate commented on crypto/src/Cardano/Crypto/ProtocolMagic.hs
> +{-# LANGUAGE ViewPatterns               #-}
I don't think you're using any `ViewPatterns`, so this can be removed.

2019-11-27 18:15 UTC, intricate commented on crypto/src/Cardano/Crypto/ProtocolMagic.hs
> +  where
Not sure if this is worth changing for this particular definition since a bunch of other `pattern` definitions in the codebase are now following the above convention.

2019-11-27 18:15 UTC, intricate commented on crypto/src/Cardano/Crypto/ProtocolMagic.hs
> +  , pattern ProtocolMagicId
Wouldn't it be cleaner to export this as part of the `ProtocolMagicId` data type export?

```
module Cardano.Crypto.ProtocolMagic
  ( ProtocolMagicId (ProtocolMagicId, unProtocolMagicId)
  , ...
```
That way, you wouldn't need to use `PatternSynonyms` along with the `pattern` keyword wherever importing it.

@redxaxder @dnadales @mhuesch: Thoughts?

2019-11-27 18:15 UTC, intricate commented on crypto/src/Cardano/Crypto/ProtocolMagic.hs
> +{-# LANGUAGE ViewPatterns               #-}
Also, these `LANGUAGE` pragmas are now unsorted.

2019-11-27 18:15 UTC, intricate commented on crypto/src/Cardano/Crypto/ProtocolMagic.hs
> +{-# LANGUAGE NamedFieldPuns             #-}
I don't think you're using any `NamedFieldPuns`, so this can be removed.

2019-11-27 18:15 UTC, intricate commented on cardano-ledger/test/Test/Cardano/Chain/Update/Example.hs
> +import Cardano.Crypto (pattern ProtocolMagicId, hash)
If the `ProtocolMagicId` pattern were exported as part of the `ProtocolMagicId` data type, you would be able to write:
```
import Cardano.Crypto (ProtocolMagicId(..), hash)
```

2019-11-27 18:26 UTC, redxaxder commented on cardano-ledger/test/Test/Cardano/Chain/Update/Example.hs
> +import Cardano.Crypto (pattern ProtocolMagicId, hash)
Oh really? I didn't know you could do that!

2019-11-27 18:33 UTC, intricate commented on cardano-ledger/test/Test/Cardano/Chain/Update/Example.hs
> +import Cardano.Crypto (pattern ProtocolMagicId, hash)
I only learned that a few days ago tbh

2019-11-28 13:43 UTC, intricate commented on crypto/src/Cardano/Crypto/ProtocolMagic.hs
> +  , pattern ProtocolMagicId
Looks like @redxaxder addressed this.

2019-12-02 11:31 UTC, mhuesch reviewed
LGTM, I see that Luke has requested some changes so I'll just comment rather than approve.

2019-12-02 13:16 UTC, intricate requested changes
Good work. Just looks like some leftover `PatternSynonyms` `LANGUAGE` pragmas to remove.

2019-12-02 13:16 UTC, intricate commented on cardano-ledger/src/Cardano/Chain/Block/Block.hs
> -  , pattern Block
:+1: Thanks for going through the other smart constructors in the project and adjusting this.

2019-12-02 13:16 UTC, intricate commented on cardano-ledger/src/Cardano/Chain/Delegation/Payload.hs
>  {-# LANGUAGE PatternSynonyms            #-}
We can remove this `PatternSynonyms`

2019-12-02 13:16 UTC, intricate commented on cardano-ledger/src/Cardano/Chain/UTxO/TxWitness.hs
>  {-# LANGUAGE PatternSynonyms     #-}
We can remove this `PatternSynonyms`

2019-12-02 13:16 UTC, intricate commented on cardano-ledger/test/Test/Cardano/Chain/Delegation/Example.hs
> +
We can remove this `PatternSynonyms`

2019-12-02 13:16 UTC, intricate commented on crypto/test/Test/Cardano/Crypto/Dummy.hs
> +{-# LANGUAGE PatternSynonyms #-}
We can remove this `PatternSynonyms`

2019-12-02 13:16 UTC, intricate commented on crypto/test/Test/Cardano/Crypto/Example.hs
> +{-# LANGUAGE PatternSynonyms #-}
We can remove this `PatternSynonyms`

2019-12-02 13:16 UTC, intricate commented on crypto/test/Test/Cardano/Crypto/Gen.hs
> +{-# LANGUAGE PatternSynonyms #-}
We can remove this `PatternSynonyms`

2019-12-02 13:16 UTC, intricate commented on crypto/test/Test/Cardano/Crypto/CBOR.hs
> +{-# LANGUAGE PatternSynonyms     #-}
We can remove this `PatternSynonyms`

2019-12-03 15:42 UTC, redxaxder commented on cardano-ledger/src/Cardano/Chain/Delegation/Payload.hs
>  {-# LANGUAGE PatternSynonyms            #-}
I got rid of a bunch of them, but this one in particular has to stay because a pattern is being defined in this file. Same for the one below.

2019-12-03 16:05 UTC, intricate approved these changes
LGTM. Great work :100:

2019-12-03 16:14 UTC, redxaxder commented
bors r+

2019-12-03 17:47 UTC, merged