Add generic `ToJSON` instances
input-output-hk/cardano-ledger-byron pull request #713
Opened 2020-02-05 20:35 UTC by Jimbo4350

Generic `ToJSON` instances have been added to debug blocks, txs, delegation certificates and update proposals (and their subtypes where necessary).

2020-02-05 21:37 UTC, erikd requested changes

2020-02-05 21:37 UTC, erikd commented on cardano-ledger/src/Cardano/Chain/Common/Attributes.hs
> +instance ToJSON LBS.ByteString where
I presume this is the reason for the `-fno-warn-orphans`.

Probably best to define all these orphan instances in their own module so that we do not have orphans and non-orphans in the same file.

, but you could avoid that, by pulling those instances from somewhere else.

2020-02-06 13:14 UTC, Jimbo4350 commented on cardano-ledger/src/Cardano/Chain/Common/Attributes.hs
> +instance ToJSON LBS.ByteString where
@erikd changes made

2020-02-10 10:06 UTC, nc6 reviewed
Comment only: I usually don't care about orphans, but I'm a little worried here where the orphan is for something as generic as `ToJSON ByteString`. I've suggested another approach; let me know if it's plausible. If not, I'll approve the PR

2020-02-10 10:06 UTC, nc6 commented on cardano-ledger/src/Cardano/Chain/Orphans.hs
> +  toJSON bs = String . toS $ LChar8.unpack bs
Creating a ToJSON orphan instance for something as generic as bytesting makes me a little worried that this will come around to bite us later. If it's needed just for one type, can we not just fold the bytestring encoder into that type?

2020-02-10 10:06 UTC, nc6 commented on cardano-ledger/src/Cardano/Chain/Orphans.hs
> +  toJSON bs = String . toS $ Char8.unpack bs
Ditto

2020-02-10 11:16 UTC, Jimbo4350 commented on cardano-ledger/src/Cardano/Chain/Orphans.hs
> +  toJSON bs = String . toS $ LChar8.unpack bs
@nc6 fair point, I'll make the changes.

2020-02-11 16:01 UTC, Jimbo4350 commented
> Comment only: I usually don't care about orphans, but I'm a little worried here where the orphan is for something as generic as `ToJSON ByteString`. I've suggested another approach; let me know if it's plausible. If not, I'll approve the PR

@nc6 Done

2020-02-12 09:27 UTC, erikd approved these changes

2020-02-12 09:28 UTC, Jimbo4350 commented
bors r+

2020-02-12 09:40 UTC, nc6 approved these changes

2020-02-12 14:36 UTC, Jimbo4350 commented
bors r+

2020-02-13 10:13 UTC, merged