Document the address discrimination problem from cardano-sl (NetworkMagic)
input-output-hk/cardano-ledger-byron pull request #755
Opened 2020-03-24 17:16 UTC by intricate

2020-03-24 21:38 UTC, erikd requested changes
Would like to see `ProtocolMagic` show here. The other comment is mostly a question.

2020-03-24 21:38 UTC, erikd commented on doc/network-magic.md
> +  | RequiresMagic
I have always wondered why we need this level of indirection. Would it not be possible to use a `NetworkMagic` value in the node configuration?

2020-03-24 21:38 UTC, erikd commented on doc/network-magic.md
> +We also added a `RequiresNetworkMagic` field to the `ProtocolMagic` data type. The `ProtocolMagic` data type would now contain two fields for which values would be specified in the node's configurati
Probably useful to show that `ProtocolMagic` type here.

2020-03-25 01:52 UTC, intricate commented on doc/network-magic.md
> +We also added a `RequiresNetworkMagic` field to the `ProtocolMagic` data type. The `ProtocolMagic` data type would now contain two fields for which values would be specified in the node's configurati
I was considering that, but it's a bit more complicated in `cardano-ledger` since it's actually an "annotated" `ProtocolMagic` (`AProtocolMagic`) :sweat_smile::

```
data AProtocolMagic a = AProtocolMagic
  { getAProtocolMagicId      :: !(Annotated ProtocolMagicId a)
  , getRequiresNetworkMagic :: !RequiresNetworkMagic
  } deriving (Eq, Show, Generic, NFData, NoUnexpectedThunks)
```

Perhaps I'll just show a simplified version of it that gets the point across:

```
data ProtocolMagic = ProtocolMagic !ProtocolMagicId !RequiresNetworkMagic
```

2020-03-25 02:01 UTC, intricate commented on doc/network-magic.md
> +  | RequiresMagic
So we could have gone that route and instead allow the `NetworkMagic` value to be specified in the configuration, e.g.:
```
networkMagic: NetworkTestnet 1337
```
or
```
networkMagic: NetworkMainOrStage
```

However, we would still need to specify the protocol magic value in the configuration since it wouldn't be known for the mainnet or staging case (`NetworkMainOrStage`). Then that opens up the possibility that the `NetworkMagic` value could be configured to something different than the protocol magic (which would be invalid).

Because of this, we figured it'd be easier to derive the `NetworkMagic` value from the configured `ProtocolMagic`.

However, an alternative would be to define `NetworkMagic` like this:

```
data NetworkMagic
  = NetworkMainnet
  | NetworkStaging
  | NetworkTestnet !Word32
```

... and hardcode the protocol magic values for mainnet and staging. That way, you could just use `NetworkMagic` in the configuration.

2020-03-25 02:03 UTC, intricate commented on doc/network-magic.md
> +  | RequiresMagic
So we could have gone that route and instead allow the `NetworkMagic` value to be specified in the configuration, e.g.:
```
networkMagic: NetworkTestnet 1337
```
or
```
networkMagic: NetworkMainOrStage
```

However, we would still need to specify the protocol magic value in the configuration since it wouldn't be known for the mainnet or staging case (`NetworkMainOrStage`). That would then open up the possibility for the `NetworkMagic` value to be configured to something different than the protocol magic. E.g., someone could set:

```
networkMagic: NetworkTestnet 1337
protocolMagic: 12345
```

... which would be invalid.

Because of this, we figured it'd be easier to derive the `NetworkMagic` value from the configured `ProtocolMagic`.

However, an alternative would be to define `NetworkMagic` like this:

```
data NetworkMagic
  = NetworkMainnet
  | NetworkStaging
  | NetworkTestnet !Word32
```

... and hardcode the protocol magic values for mainnet and staging. That way, you could just use `NetworkMagic` in the configuration.

2020-03-25 02:16 UTC, erikd commented on doc/network-magic.md
> +We also added a `RequiresNetworkMagic` field to the `ProtocolMagic` data type. The `ProtocolMagic` data type would now contain two fields for which values would be specified in the node's configurati
Yeah, that makes sense, as long as you do note that its a simplified version.

2020-03-25 02:17 UTC, erikd commented on doc/network-magic.md
> +  | RequiresMagic
I actually like that 3 constructor version.

2020-03-25 02:19 UTC, intricate commented on doc/network-magic.md
> +  | RequiresMagic
Deleted my previous reply which was totally wrong :smile:.

So we could have gone that route and instead allowed the `NetworkMagic` value to be specified in the configuration, e.g.:
```
networkMagic: NetworkTestnet 1337
```
or
```
networkMagic: NetworkMainOrStage
```

However, because the protocol magic is already specified in the genesis config, this would then open up the possibility for the `NetworkMagic` value (in the `NetworkTestnet` case) to be configured to a value different than that of the protocol magic (which would be invalid). 

Overall, it seemed cleaner to introduce `RequiresNetworkMagic`, which would be specified in the node's configuration, and derive the `NetworkMagic` value from the protocol magic value specified in the genesis config, when needed.

2020-03-25 09:36 UTC, dnadales commented on doc/network-magic.md
> +# Address Discrimination (`NetworkMagic`)
Maybe break lines at 80 characters, to make it easy to review this and future PR's.

2020-03-25 09:36 UTC, dnadales commented on doc/network-magic.md
> +# Address Discrimination (`NetworkMagic`)
I guess most editors would come with a command to automatically do this.

2020-03-25 09:37 UTC, dnadales commented on doc/network-magic.md
> +Address discrimination was a problem in the original [`cardano-sl`](https://github.com/input-output-hk/cardano-sl) implementation that originally came to our attention in mid-2018. This document brie
```suggestion
Address discrimination was a problem in the original [`cardano-sl`](https://github.com/input-output-hk/cardano-sl) implementation that came to our attention in mid-2018. This document briefly describes the problem as well as the solution implemented.
```

2020-03-25 09:38 UTC, dnadales commented on doc/network-magic.md
> +However, because pre-existing mainnet and staging addresses would not contain this new field, we had to ensure that its inclusion would be optional in order to maintain backward compatibility.
backwards compatibility?

2020-03-25 09:42 UTC, dnadales commented on doc/network-magic.md
> +  | RequiresMagic
Maybe we should explain this as well. Although I'm still not sure I get why one couldn't simply use `NetworkMagic` everywhere dispensing from the need of using `RequiresNetworkMagic`.

2020-03-25 09:44 UTC, dnadales approved these changes
Thanks Luke!

2020-03-25 09:47 UTC, dnadales commented on doc/network-magic.md
> +We also added a `RequiresNetworkMagic` field to the `ProtocolMagic` data type. The `ProtocolMagic` data type would now contain two fields for which values would be specified in the node's configurati
Oh, maybe it'd be worthwhile explaining briefly what the `ProtocolMagic` is, and what would have happened if `RequiresNetworkMagic` was not included here. (Another way of saying why its inclusion in this data type is important).

2020-03-25 14:06 UTC, intricate commented on doc/network-magic.md
> +# Address Discrimination (`NetworkMagic`)
Oops, my bad.

2020-03-25 14:55 UTC, intricate commented on doc/network-magic.md
> +However, because pre-existing mainnet and staging addresses would not contain this new field, we had to ensure that its inclusion would be optional in order to maintain backward compatibility.
Did I misuse the term here or are you suggesting a spelling error, i.e. "backward" -> "backwards".

2020-03-25 15:26 UTC, dnadales commented on doc/network-magic.md
> +However, because pre-existing mainnet and staging addresses would not contain this new field, we had to ensure that its inclusion would be optional in order to maintain backward compatibility.
No you're right: "backward compatibility" is fine!

2020-03-25 16:52 UTC, intricate commented on doc/network-magic.md
> +We also added a `RequiresNetworkMagic` field to the `ProtocolMagic` data type. The `ProtocolMagic` data type would now contain two fields for which values would be specified in the node's configurati
Will do.

2020-03-26 12:11 UTC, Jimbo4350 approved these changes
LGTM

2020-04-08 23:15 UTC, erikd submitted a review, later dismissed
Two really minor changes required, and once those are sorted, please merge away.

2020-04-08 23:15 UTC, erikd commented on doc/network-magic.md
> +nitty-gritty details can still be found under issues `CO-353` and `CO-354`.
This is a public document, so its probably worth mentioning that those issues are in the "internal IOHK ???? bugtracker".

2020-04-08 23:15 UTC, erikd commented on doc/network-magic.md
> +in a loss of those funds.
I would replace "would" with "could" (If the person doing that transfer had access to the private keys of the destiination address they are still recoverable.)

2020-04-09 18:05 UTC, intricate commented
bors r+

2020-04-09 19:03 UTC, merged