Redxaxder/wip
input-output-hk/cardano-ledger-byron pull request #94
Opened 2018-11-01 19:30 UTC by redxaxder

For review only. Do not merge.

2018-11-01 21:22 UTC, ruhatch reviewed
Looks really good. I'd like to get some more eyes on this and also some more documentation, but should be able to get this in tomorrow.

2018-11-01 21:22 UTC, ruhatch commented on binary/src/Cardano/Binary/Class/Annotated.hs
> +annotatedDecoder d = flip fmap (D.decodeWithByteSpan d) $ \(x, start, end) ->
`D.decodeWithByteSpan <&> \(x, start end) -> ...`?

2018-11-01 21:22 UTC, ruhatch commented on src/Cardano/Chain/Block/Header.hs
> +header pm hh p cd ehd = AHeader
I'm not sure I like this being called `header`, but I know `mkHeader` is also taken. We probably shouldn't have been exposing the `Header` constructor before and this opens that up too. You could simply inline this to it's only usage site and then you can change back `h`s to `header`s.

2018-11-01 21:22 UTC, ruhatch commented on src/Cardano/Chain/Block/Header.hs
> +      (consensusSlot . headerConsensusData $ h)
I think there's a `headerSlot` and `headerDifficulty` to shorten these

2018-11-01 21:22 UTC, ruhatch commented on test/Test/Cardano/Chain/Block/Header.hs
> +  let bytes = (serializeEncoding . encode) header
Couldn't you just use `serialize` here?

2018-11-01 21:22 UTC, ruhatch commented on test/Test/Cardano/Chain/Block/Header.hs
> +    pure $ map (const ()) header
Maybe `pure (() $> header)`? Not sure if that's actually more readable though...

2018-11-02 14:25 UTC, redxaxder commented on crypto/src/Cardano/Crypto/Signing/Check.hs
> +
This function should ultimately replace all uses of checkSig above.

2018-11-02 14:27 UTC, redxaxder commented on crypto/src/Cardano/Crypto/Signing/Signing.hs
> +    (psigSig psig)
Replaces `proxyVerify`

2018-11-02 14:36 UTC, redxaxder commented on src/Cardano/Chain/Block/Header.hs
> +  } deriving (Eq, Show, Generic, NFData, Functor)
All values which need their hash or signature verified are replaced with an annotated version.
The types we use in place of `a` are:
 - `()` for headers constructed locally
 - `ByteSpan` for the return type of a decoder
 - `ByteString` for checkable values.

2018-11-02 14:43 UTC, redxaxder commented on src/Cardano/Chain/Block/Header.hs
> +
We can't move entirely away from constructing things during verification since the bytestring signed during the construction of a header is the above, rather than a substring of the encoded header.

2018-11-02 15:04 UTC, parsonsmatt requested changes
There's a term that is still `undefined`. Otherwise, the design and implementation here looks fantastic.

2018-11-02 15:04 UTC, parsonsmatt commented on binary/src/Cardano/Binary/Class/Annotated.hs
> +  decodeFullDecoder lbl decoder bytes
This is strictly a style thing, but I usually like the way that:

```haskell
fmap (BSL.toStrict . slice bytes) <$> decodeFullDecoder lbl decoder bytes
```

as it saves a few characters and avoids the cluttered `fmap.fmap` thing. I'd prefer to see `(fmap . fmap)`, but I don't have a strong opinion.

2018-11-02 15:04 UTC, parsonsmatt commented on crypto/src/Cardano/Crypto/Signing/Signing.hs
> +{-# WARNING proxyVerify "to remove" #-}
Not strictly necessary but I'd make this a `DEPRECATED` pragma instead and include the note "use `proxyVerifyAnnotated` instead"

2018-11-02 15:04 UTC, parsonsmatt commented on src/Cardano/Chain/Block/Header.hs
> +headerExtraData = unAnnotated . aHeaderExtraData
I love this change, as it extends the codebase in new and interesting ways, but not in a way that requires a massive and invasive edit to every bit of code that uses the old variant! :smile:

2018-11-02 15:04 UTC, parsonsmatt commented on src/Cardano/Chain/Block/Header.hs
> +verifyHeader = undefined
Is this a `TODO`? I usually prefer `error "some informative note here"` for that sort of thing :slightly_smiling_face:

2018-11-02 15:04 UTC, parsonsmatt commented on src/Cardano/Chain/Block/Header.hs
> +      -- It is hard coded here because the signed bytes included it as an implementation artifact
Is there any way we can factor this magic constant out, or re-derive it somehow? I'd hate for a regression to sneak in if that value ever changes. I imagine it would be extremely difficult to debug.

2018-11-02 15:04 UTC, parsonsmatt commented on stack.yaml
> +      - cborg
Can we include a note on why we are pulling in a Git dependency, along with a link to the PR that upstreams this?

2018-11-02 15:04 UTC, parsonsmatt commented on test/Test/Cardano/Chain/Block/Header.hs
> +    pure $ map (const ()) header
This is also `void :: Functor f => f a -> f ()` :smile:

2018-11-02 15:12 UTC, redxaxder commented on src/Cardano/Chain/Block/Header.hs
> +verifyHeader = undefined
This is slated to be deleted entirely. It's still in use in other code, so this just makes the PR compile.

2018-11-02 15:18 UTC, redxaxder commented on crypto/src/Cardano/Crypto/Signing/Signing.hs
> +{-# WARNING proxyVerify "to remove" #-}
I would like to delete the current `proxyVerify` an replace it with a new `proxyVerify` which has the type/implementation of `proxyVerifyAnnotated`.

2018-11-02 15:18 UTC, redxaxder commented on binary/src/Cardano/Binary/Class/Annotated.hs
> +  decodeFullDecoder lbl decoder bytes
I have a mental 'chunk' for chained fmaps `(fmap . fmap . fmap)` to recognize what they do. N of them goes N functors deep.

The mix between `fmap` and `<$>` doesn't trigger it for me the same way, so it takes a bit longer to parse it. This might be just a personal mental quirk, though.

2018-11-02 15:26 UTC, dnadales commented on binary/src/Cardano/Binary/Class/Annotated.hs
> +{-# LANGUAGE DeriveAnyClass     #-}
Maybe some comments on what the `Annotated` module contains, and what the exposed functions are would be nice.

2018-11-02 15:32 UTC, redxaxder commented on src/Cardano/Chain/Block/Header.hs
> +      -- It is hard coded here because the signed bytes included it as an implementation artifact
My interpretation of the situation we're in is the following.

Two decisions were made earlier:
  - The Byron implementors decided that a CBOR list gets signed instead of a substring of the header
  - The `cborg` implementors chose this particular byte as their encoding of the list length. (The CBOR specification has multiple encodings of the same integer)

If the value used in the `cborg` library ever changes, we will still want to use the earlier value to maintain compatibility with older blocks.

We're permanently saddled with caring about the particular byte `"\133"` :(.

Do you have an idea for how to make this better?

2018-11-02 15:32 UTC, ruhatch commented on src/Cardano/Chain/Block/Header.hs
> +      -- It is hard coded here because the signed bytes included it as an implementation artifact
We could use `serializeEncoding (encodeListLen 4)`?

2018-11-02 15:44 UTC, dnadales commented on crypto/src/Cardano/Crypto/Signing/Signing.hs
> +    (mconcat ["01", CC.unXPub issuerPk, signTag pm t, annotation m])
No more re-serialization. Nice!

2018-11-02 15:45 UTC, dnadales reviewed
LGTM!

2018-11-02 16:04 UTC, redxaxder commented on src/Cardano/Chain/Block/Header.hs
> +      -- It is hard coded here because the signed bytes included it as an implementation artifact
The plan for Shelly is to stop requiring canonical CBOR.

(nb: "canonical" here does not refer to a standard. It refers to a particular set of choices made for our protocol.)

There are multiple bytes that implementors can choose from to encode the same CBOR integer, and these are used to encode the length of lists. For this particular CBOR list, the byte chosen by the node isn't transmitted as part of the payload. 

So it isn't enough to specify that this is a byte corresponding to list length 5. It has to be this exact byte. Otherwise the receiving node cannot validate the signature.

2018-11-20 15:10 UTC, ruhatch commented
This was a PR for review only, so I'm closing it.

2018-11-20 15:10 UTC, closed without merging